### ISSUE TITLE
Problem in create_region with Maxwell2d / MagnetostaticXY

### ISSUE THREAD

**Issue by BLeistr** [pyansys/pyaedt#1018]
In Maxwell 2D XY there are problems with the creation of a region. The settings for Z are always used, because the variable self._app.xy_plane in create_region in pyaedt\modeler\Primitives2D.py is nevertheless FALSE.

I use:
m2d = Maxwell2d(specified_version="2022.1", solution_type="MagnetostaticXY")
region = m2d.modeler.primitives.create_region([100,300,100,300])

I think it can also be solved with:
        if is_number(pad_percent):
            pad_percent = [pad_percent] * 6
        else:
            pad_percent = [pad_percent[0], pad_percent[1], pad_percent[1], pad_percent[2], pad_percent[3], pad_percent[3]]
Because the entries at the unused coordinates do not interfere.

**Comment by maxcapodi78** [comment]
Fixed in #1042 The problem was not in create_region method but in the xy_value property that now is not anymore a string but a bool and the method was ignoring it.
