### ISSUE TITLE
Creation of PostProcessingVariable

### ISSUE THREAD

**Issue by BLeistr** [pyansys/pyaedt#1019]
Is there already a possibility to create postprocessing variables?

![grafik](https://user-images.githubusercontent.com/98037049/161067016-bfaf0d4d-5b28-499d-86df-d070baeb1aaf.png)

**Comment by maxcapodi78** [comment]
Hello
yes.
hfss.variable_manager.set_variable("myvar", "1mm", postprocessing=True)

or  by giving a name with prefix post_

hfss["post_myvar"] = "1mm"
