### ISSUE TITLE
[Maxwell2d] Assign EndConnection

### ISSUE THREAD

**Issue by mehs1006** [pyansys/pyaedt#1024]
Dear All,
I try to implement the function of "Assign End Connection" by PyAEDT, but I cannot find it.

![image](https://user-images.githubusercontent.com/102974184/161560347-c2c8f3df-51ac-4a05-96fe-9a3752ea1264.png)

I attach the script of iPython which is mainly recorded from Maxwell2d below.
![image](https://user-images.githubusercontent.com/102974184/161563841-960fd977-5b51-4b38-bdd2-46786c96c276.png)

Please help me with it.
Thank you.

BR,
/Meng-Ju

**Comment by maxcapodi78** [comment]
Added new method assign_end_connection in #1043
