### ISSUE TITLE
[Maxwell2d] symmetry multiplier

### ISSUE THREAD

**Issue by mehs1006** [pyansys/pyaedt#1025]
Hi,

I tried to use the module of "symmetry_multiplier" in PyAEDT to make the below design setting.
![image](https://user-images.githubusercontent.com/102974184/161588570-b29fdfde-3b2c-4405-9c7d-91385a17239b.png)

But it seems this function doesn't work for resetting "Multiplier" to another value.

Please guide me on how to set the "symmetry_multiplier".
Thanks a lot.

BR,
/Meng-Ju

**Comment by maxcapodi78** [comment]
Hello @mehs1006 I've added 2 methods in #1044 
app.change_design_settings({"Multiplier": 2})
app.change_simmetry_multiplier(1)
The first one is generic and can be used to chage any design settings by passing as a dictionary. The second is specific for simmetry multiplier

**Comment by mehs1006** [comment]
Hi @maxcapodi78 ,
The first one is even better and more flexible!
Thank you. 👍
