### ISSUE TITLE
Make the arguments in globalMeshSettings() in icepak.py editable

### ISSUE THREAD

**Issue by linmingchih** [pyansys/pyaedt#1028]
![image](https://user-images.githubusercontent.com/13580731/161923750-e46036c6-d58e-41c1-9552-e21379fccf74.png)

**Comment by maxcapodi78** [comment]
Hello @linmingchih this is already possible.

`ipk = Icepak()
ipk.mesh.global_mesh_region.UserSpecifiedSettings=True
ipk.mesh.global_mesh_region.MaxLevels = 3
ipk.mesh.global_mesh_region.update()`
