### ISSUE TITLE
Edb dependent on .NET Regional Settings

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [pyansys/pyaedt#1030]
If the decimal delimiter in Windows OS is set to comma ",", then some EDB methods and properties are corrupted. I found this in 
`class EdbPadstacks(object):` in the padstack.py module.  The property `rotation` in the 
```python
    def create_padstack()
```
method cannot be parsed if the .NET delimiter is set to comma.

**Comment by svandenb-dev** [comment]
Hi @dcrawforAtAnsys,
I think this is not only concerning the this command and has to be addressed at higher level in Pyaedt architecture. We will see how to handle this

**Comment by svandenb-dev** [comment]
we will address this in pyedb. This limitation has been communicated to EDB Api dev team
