### ISSUE TITLE
Time-dependent variables and relative CS causing issues for Maxwell2d

### ISSUE THREAD

**Issue by JuliusSaitz** [pyansys/pyaedt#1031]
Let's have a Maxwell 2D (3D) transient design and create a variable ts = time:

![image](https://user-images.githubusercontent.com/97598531/162181389-c60761f9-9f21-4250-a466-c45a926dbd3d.png)

Create a relative CS:

![image](https://user-images.githubusercontent.com/97598531/162201373-fdee6217-86b0-4619-b2f6-6fb0bf60c787.png)

For one of the angles, create a variable:

![image](https://user-images.githubusercontent.com/97598531/162201739-e01c598d-96c2-488e-8efd-b85e4568262d.png)

![image](https://user-images.githubusercontent.com/97598531/162201903-a354521f-6260-4325-92b0-4fc22f77837b.png)

Now, run the following: m2d = Maxwell2d(designname="01",specified_version="2022.1"). This produces the error messages:

![image](https://user-images.githubusercontent.com/97598531/162202266-5501256d-fcea-42f0-8614-7b73529c7bb0.png)

If the CS definition is replaced in the following way:

![image](https://user-images.githubusercontent.com/97598531/162202651-5955cf38-59e7-4529-bead-73bbae54d3f7.png)

and we run m2d again, this time there is a different error:

![image](https://user-images.githubusercontent.com/97598531/162202858-e0cb1554-385f-4ce2-841e-eff655b32330.png)

If the angle definition is a plain number:

![image](https://user-images.githubusercontent.com/97598531/162203074-0b42b2ac-3263-45ac-81dc-d2fae2c81f61.png)

no error messages are displayed and everything works as expected.

This means, that for some reason when using pyaedt function Maxwell2d, there are errors when there is a time dependent variable and a CS with an angle defined by a variable.

**Comment by maxcapodi78** [comment]
Hi @JuliusSaitz Fixed in #1045
