### ISSUE TITLE
Working with variables does not work for Maxwell Circuit

### ISSUE THREAD

**Issue by JuliusSaitz** [pyansys/pyaedt#1037]
The following commands produce an error:

mc = MaxwellCircuit(designname="my_Maxwell_circuit_design",specified_version="2022.1") OK
mc["var3"]="10mm" error
v_circuit=mc.variable_manager OK
var_circuit = v_circuit.variable_names error
print(v_circuit.independent_variable_names) error

These functions are important for creating and listing Maxwell Circuit Editor variables.

**Comment by maxcapodi78** [comment]
Hi @JuliusSaitz it has been fixed in #1046 . Maxwell variable manager use different syntax from any other AEDT tool.
