### ISSUE TITLE
Access to port name inside a Lumped Port

### ISSUE THREAD

**Issue by enrique-rc** [pyansys/pyaedt#1068]
Hi,

After generating an excitation of type "Lumped Port", how can I access to its port and the name of the port (usually ends in _T1)?

Thank you!!!

**Comment by Samuelopez-ansys** [comment]
Hi @enrique-rc , if you created the lumped port using 'port = aedtapp.create_lumped_port_to_sheet', port should have this info.

port.name

If you need the terminal name, the only way is port2.name + "_T1"

In 'aedtapp. excitations' you will find the list of terminals as well

**Comment by Samuelopez-ansys** [comment]
Hi @enrique-rc ,

Is this issue solved?

**Comment by enrique-rc** [comment]
Hi @Samuelopez-ansys , it is solved. Thank you for your support.
