### ISSUE TITLE
Got some problem in change motions parameters 😭 

### ISSUE THREAD

**Issue by tako861225** [pyansys/pyaedt#1099]
hello ~ 
I got some problem on changing motions parameters 
First I used ``assign_rotate_motion`` ,then I want to change the parameters.
![image](https://user-images.githubusercontent.com/51187903/165321946-9875b027-045b-4a45-b67c-c7d1daffdf71.png)
I changed all the parameters before but they got the same error
![image](https://user-images.githubusercontent.com/51187903/165322283-51318237-65a8-40bb-8ada-7499f556d5b3.png)
Also I check the props parameters name that make sure I'm not typing error
![image](https://user-images.githubusercontent.com/51187903/165322696-079ba89f-3e83-4c49-b282-918b3bcff53b.png)
😢 
thanks a lot 
Evelyn

**Comment by maxcapodi78** [comment]
Hello Evelyn @tako861225 I've fixed your issue. The problem is that the motion setup name is fixed and cannot be changed so I was storing wrong reference name internally.
