### ISSUE TITLE
Maxwell3d.assign_coil shows errors

### ISSUE THREAD

**Issue by JuliusSaitz** [pyansys/pyaedt#1101]
This command:

m3d.assign_coil(input_object=face,conductor_number=1000,name="Tx_coil",polarity="positive")

works OK and does what is needed, but shows the following errors:

![image](https://user-images.githubusercontent.com/97598531/165468943-dcf1f151-014e-43ab-b8c5-6c5e3082185b.png)

**Comment by tako861225** [comment]
Hi ~ 
I got the same problem before 
![image](https://user-images.githubusercontent.com/51187903/165470882-d1a257df-2564-4779-a5dd-557970425551.png)
1.``input_object`` need to be list 
     change "face" to "[face]"
2. polarity="positive" ==> polarity="Positive"

hopefully this can helps you 
Evelyn
