### ISSUE TITLE
Add wheelhouse to CI/CD

### ISSUE THREAD

**Issue by akaszynski** [pyansys/pyaedt#1110]
In support of offline deployment, we need to add a wheelhouse generation and deployment step to our CI/CD. This has been implemented in PyMAPDL:

https://github.com/pyansys/pymapdl/blob/45c89eab352993c3bac237e73e3558974653af84/.github/workflows/ci.yml#L93-L107

This creates *zip artifacts and uploads them on each release step. You'll need to add in additional "smoke tests" for Python 3.7 - 3.9 on Windows and Linux to generate the necessary wheels.

Finally, add or modify a release step to deploy those artifacts automatically for the release. See:

https://github.com/pyansys/pymapdl/blob/45c89eab352993c3bac237e73e3558974653af84/.github/workflows/ci.yml#L318-L361

Specifically:
https://github.com/pyansys/pymapdl/blob/45c89eab352993c3bac237e73e3558974653af84/.github/workflows/ci.yml#L342-L349

**Comment by MaxJPRey** [comment]
@akaszynski I am on it.
