### ISSUE TITLE
Batch file should update PersonalLib package

### ISSUE THREAD

**Issue by Samuelopez-ansys** [pyansys/pyaedt#1220]
When the user performs:

- pyaedt_with_IDE.bat -f
or
- pyaedt_with_IDE.bat -u

PyAEDT is updated correctly in the virtual environment, but the copy in PersonalLib does not change.

**Comment by Samuelopez-ansys** [comment]
@maxcapodi78

**Comment by Alberto-DM** [comment]
The one in PersonalLib is not a copy, is a symbolic link (simlink) to the pyaedt installation folder. So there is no need to update it as it is pointing to the updated folder.
