### ISSUE TITLE
Bounding box should not accept 5 elements.

### ISSUE THREAD

**Issue by MaxJPRey** [pyansys/pyaedt#1304]
In the Model 2D, if the bounding box contains 5 coordinates, an exception is not raised while it should be.
https://github.com/pyansys/pyaedt/blob/42cd90e24cf3876f7c7f6818156d51559602276d/pyaedt/modeler/Model2D.py#L159

**Comment by Samuelopez-ansys** [comment]
@gmalinve

**Comment by MaxJPRey** [comment]
@Samuelopez-ansys This was fixed in #1305 .
I updated the comment of the pull request to link it with this issue.
Thanks.
