### ISSUE TITLE
Support setting absolute dimensions for dielectric and airbox extents

### ISSUE THREAD

**Issue by isaacansys** [pyansys/pyaedt#1317]
### Description of the feature

The EDB and HFSS 3D Layout support either multiple-based or absolute dimensions for dielectric and airbox extents, but the current SimulationConfiguration implementation only supports multiple-based settings at this time.

### Steps for implementing the feature

1. Add new bool properties to SimulationConfiguration to indicate whether the dielectric, airbox horizontal, airbox negative vertical, and airbox positive vertical extents are multiples (True to match EDB API) or absolute dimensions (False).
2. Use these properties in configure_hfss_extents in pyaedt/edb_core/hfss.py to populate the tuples set on the HFSSExtentsInfo object.

**Comment by maxcapodi78** [comment]
@svandenb-dev can you take a look to this request?

**Comment by svandenb-dev** [comment]
yes I will take a look

**Comment by svandenb-dev** [comment]
@isaacansys done
