### ISSUE TITLE
Analysis RMxprt methods to check consistency not used

### ISSUE THREAD

**Issue by jleonatti** [pyansys/pyaedt#135]
https://github.com/pyansys/PyAEDT/blob/5dd9780ad0c3dc23ce1e2c09fc341ab857f3334e/pyaedt/application/AnalysisRMxprt.py#L113-L128

The two methods above are not referenced. Can they be removed?

Also, there are several places where multiple methods are commented out like here:
https://github.com/pyansys/PyAEDT/blob/5dd9780ad0c3dc23ce1e2c09fc341ab857f3334e/pyaedt/application/AnalysisRMxprt.py#L105-L112
Is it okay to remove these or are they needed?

**Comment by Samuelopez-ansys** [comment]
@pblarsen-ansys could you check this issue? If it is already resolved, you could proceed to close this issue. Thanks!

**Comment by Samuelopez-ansys** [comment]
@gmalinve If you have time could you please check if these methods could be removed? No rush, if they could be removed, close this Issue. Thanks!

**Comment by gmalinve** [comment]
@Samuelopez-ansys no commented out methods anymore. The two methods mentioned at the beginning override two other methods in Design.py.
