### ISSUE TITLE
assign_current in TransientAphiFormulation solution type

### ISSUE THREAD

**Issue by Andrew993-chang** [pyansys/pyaedt#1370]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

In TransientAphiFormulation, while i'm using assign_current, there always shows an error information like the followings. 
[error] Script macro error: Excitation 'current_in': Active design doesn't support phase in excitation.
How can I correctly assign the current?

### Steps To Reproduce

project.assign_current(transmitter_in, amplitude=str(current) + "*sin(2*pi*" + str(frequency) + "*$f0*Time)",
                           name="current_in", solid=False)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.9

### Installed packages

pyaedt                    0.4.51

**Comment by maxcapodi78** [comment]
implemented in #1483
