### ISSUE TITLE
Icepak.oboundary.update_assignment()

### ISSUE THREAD

**Issue by sheabenter** [pyansys/pyaedt#1372]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

When trying to update a boundary assignment in Icepak using oboundary.update_assignment() method, I get the error below.  I get the same result in 2022 R1 and R2.

```
pyaedt error: Method update_assignment Failed:  General or AEDT Error. Please Check again
Method update_assignment Failed:  General or AEDT Error. Please Check again
pyaedt error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
(-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024381), None)
pyaedt error: Arguments Provided: 
Arguments Provided:
pyaedt error: Error in :   File "d:\aedt\.venv\lib\site-packages\pyaedt\modules\Boundary.py", line 624, in update_assignment
Error in :   File "d:\aedt\.venv\lib\site-packages\pyaedt\modules\Boundary.py", line 624, in update_assignment
pyaedt error: Check Online documentation on: https://aedtdocs.pyansys.com/search.html?q=update_assignment
Check Online documentation on: https://aedtdocs.pyansys.com/search.html?q=update_assignment
```

### Steps To Reproduce

```
boundary_obj.props['Objects'].append(new_obj.id)
boundary_obj.props['Objects'].remove(old_obj.id)
boundary_obj.update_assignment()
```

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.9

### Installed packages

aiohttp==3.8.1
aiosignal==1.2.0
anyio==3.6.1
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
async-timeout==4.0.2
attrs==21.4.0
Babel==2.10.3
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.1
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.1.0
clr-loader==0.1.7
colorama==0.4.5
cycler==0.11.0
debugpy==1.6.2
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.4
executing==0.8.3
fastjsonschema==2.15.3
fonttools==4.34.4
frozenlist==1.3.0
idna==3.3
imageio==2.19.3
importlib-metadata==4.12.0
ipykernel==6.15.1
ipython==8.4.0
ipython-genutils==0.2.0
jedi==0.18.1
Jinja2==3.1.2
json5==0.9.8
jsonschema==4.6.2
jupyter-client==7.3.4
jupyter-core==4.11.1
jupyter-server==1.18.1
jupyterlab==3.4.3
jupyterlab-pygments==0.2.2
jupyterlab-server==2.15.0
kiwisolver==1.4.3
MarkupSafe==2.1.1
matplotlib==3.5.2
matplotlib-inline==0.1.3
mistune==0.8.4
multidict==6.0.2
nbclassic==0.4.2
nbclient==0.6.6
nbconvert==6.5.0
nbformat==5.4.0
nest-asyncio==1.5.5
notebook-shim==0.1.0
numpy==1.23.0
packaging==21.3
pandas==1.4.3
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
Pillow==9.2.0
plumbum==1.7.2
prometheus-client==0.14.1
prompt-toolkit==3.0.30
psutil==5.9.1
pure-eval==0.2.2
pyaedt==0.5.0
pycparser==2.21
Pygments==2.12.0
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
pythonnet==3.0.0rc2
pytz==2022.1
pyvista==0.35.1
pywin32==304
pywinpty==2.0.6
pyzmq==23.2.0
requests==2.28.1
rpyc==5.0.1
scooby==0.5.12
Send2Trash==1.8.0
six==1.16.0
sniffio==1.2.0
soupsieve==2.3.2.post1
stack-data==0.3.0
terminado==0.15.0
tinycss2==1.1.1
tornado==6.2
traitlets==5.3.0
urllib3==1.26.10
vtk==9.1.0
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.3.3
wslink==1.6.6
yarl==1.7.2
zipp==3.8.0

**Comment by maxcapodi78** [comment]
I've fixed it
