### ISSUE TITLE
Please extend method Maxwell3D.export_3d_model to *.jpeg format

### ISSUE THREAD

**Issue by tizianrot** [pyansys/pyaedt#1378]
### Description of the feature

Please allow different export formats for the method Maxwell3d.export_3d_model, i.e. *.jpeg format.

Up to now it works only using the old APIs:
M3D = Maxwell3d(designname=dName, solution_type=sType,new_desktop_session=False)

my_oeditor = M3D.oeditor
my_oeditor.ExportModelImageToFile("C:/MyFile.jpg", 1288, 870,
                                   [
                                       "NAME:SaveImageParams",
                                       "ShowAxis:=", "True",
                                       "ShowGrid:="         , "True",
                                       "ShowRuler:="                     , "True",
                                       "ShowRegion:="                  , "Default",
                                       "Selections:="                      , "Coil1",
                                       "FieldPlotSelections:="       , "",
                                       "FitToSelections:="             , "",
                                       "FitToFieldPlotSelections:=", "",
                                       "Orientation:="                    , ""
                                   ])

**Comment by Samuelopez-ansys** [comment]
Hi @tizianrot ,

I think this API method is already wrapped:

path =aedtapp.post.export_model_picture(show_axis=True, show_grid=False, show_ruler=True)

Let me know if you see any limitations
