### ISSUE TITLE
Bug located in .q3d.modeler.thicken_sheet

### ISSUE THREAD

**Issue by priti-ashvin-shah-ibm** [pyansys/pyaedt#1382]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The direction that the polygon is drawn matters to thicken_sheet.  Counter clock wise will thicken in the direction of the thickness value using the conventional z values.  HOWEVER, if you create the poly in clockwise direction, then thickness value will become -thickness.

### Steps To Reproduce

Create_polyline two  rectangles in both clockwise and counter clock wise.  Then try to thicken_sheet with same value.  They will thicken in different directions.  

Please make it clear in the documentation as to what is expected with thicken_sheet. 

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.9

### Installed packages

addict @ file:///home/conda/feedstock_root/build_artifacts/addict_1636818143388/work
alabaster==0.7.12
anyio==3.6.1
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1640817743617/work
argon2-cffi-bindings @ file:///D:/bld/argon2-cffi-bindings_1649500527917/work
astroid==2.11.5
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1618968359944/work
atomicwrites==1.4.0
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1640799537051/work
Babel @ file:///home/conda/feedstock_root/build_artifacts/babel_1651737115240/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
beautifulsoup4 @ file:///home/conda/feedstock_root/build_artifacts/beautifulsoup4_1649463573192/work
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1649361991009/work
branca @ file:///home/conda/feedstock_root/build_artifacts/branca_1650311966802/work
brotlipy @ file:///D:/bld/brotlipy_1648854347500/work
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
certifi==2022.5.18.1
cffi @ file:///D:/bld/cffi_1636046270630/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1644853463426/work
click @ file:///D:/bld/click_1651215332191/work
click-plugins==1.1.1
cligj @ file:///home/conda/feedstock_root/build_artifacts/cligj_1633637764473/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1602866480661/work
cryptography @ file:///D:/bld/cryptography_1652967200171/work
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
Cython @ file:///D:/bld/cython_1652809486376/work
debugpy @ file:///D:/bld/debugpy_1649586532851/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
descartes==1.1.0
dill==0.3.5.1
docutils @ file:///D:/bld/docutils_1648737820009/work
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1643888246732/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1646044401614/work
fastjsonschema @ file:///home/conda/feedstock_root/build_artifacts/python-fastjsonschema_1641751198313/work/dist
Fiona==1.8.21
flit_core @ file:///home/conda/feedstock_root/build_artifacts/flit-core_1645629044586/work/source/flit_core
folium @ file:///home/conda/feedstock_root/build_artifacts/folium_1638560701663/work
fonttools @ file:///D:/bld/fonttools_1651018175663/work
GDAL==3.5.0
gdspy @ file:///D:/bld/gdspy_1649850438341/work
geopandas @ file:///home/conda/feedstock_root/build_artifacts/geopandas_1638382567988/work
h5py @ file:///D:/bld/h5py_1637965026596/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1642433548627/work
imagesize @ file:///home/conda/feedstock_root/build_artifacts/imagesize_1636492669893/work
importlib-metadata @ file:///D:/bld/importlib-metadata_1653252994979/work
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1652715758048/work
iniconfig==1.1.1
ipykernel @ file:///C:/ci/ipykernel_1647000977835/work/dist/ipykernel-6.9.1-py3-none-any.whl
ipython @ file:///D:/bld/ipython_1653755095589/work
ipython-genutils==0.2.0
ipywidgets @ file:///home/conda/feedstock_root/build_artifacts/ipywidgets_1647456365981/work
isort==5.10.1
jedi @ file:///D:/bld/jedi_1649067336192/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1651774399431/work
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1633637554808/work
json5==0.9.8
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema-meta_1651798819471/work
jupyter @ file:///D:/bld/jupyter_1637233334138/work
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1652061014773/work
jupyter-console @ file:///home/conda/feedstock_root/build_artifacts/jupyter_console_1646669715337/work
jupyter-core @ file:///D:/bld/jupyter_core_1652365483950/work
jupyter-nbgallery==2.0.0
jupyter-server==1.17.0
jupyter-sphinx==0.3.2
jupyterlab==3.4.2
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1649936611996/work
jupyterlab-server==2.14.0
jupyterlab-widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1647446862951/work
kiwisolver @ file:///D:/bld/kiwisolver_1648854574371/work
lazy-object-proxy==1.7.1
mapclassify @ file:///home/conda/feedstock_root/build_artifacts/mapclassify_1627363180059/work
MarkupSafe @ file:///D:/bld/markupsafe_1648737731599/work
matplotlib @ file:///D:/bld/matplotlib-suite_1651609712471/work
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1631080358261/work
mccabe==0.7.0
mistune @ file:///D:/bld/mistune_1635844812333/work
mpmath @ file:///home/conda/feedstock_root/build_artifacts/mpmath_1612895720168/work
munch==2.5.0
munkres==1.1.4
nbclassic==0.3.7
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1652155694429/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert-meta_1649676641343/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1651607001005/work
nbsphinx==0.8.6
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1648959695634/work
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1653162972907/work
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1650363291341/work
notebook-shim==0.1.0
numpy @ file:///D:/bld/numpy_1653325554875/work
numpydoc==1.3.1
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1637239678211/work
pandas @ file:///D:/bld/pandas_1653497263811/work
pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
patsy @ file:///home/conda/feedstock_root/build_artifacts/patsy_1632667180946/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow @ file:///D:/bld/pillow_1652815234323/work
Pint @ file:///home/conda/feedstock_root/build_artifacts/pint_1650914444525/work
platformdirs==2.5.2
pluggy==1.0.0
plumbum==1.7.2
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1649447152425/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1649130487073/work
psutil @ file:///D:/bld/psutil_1653089388778/work
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
py==1.11.0
pyaedt==0.4.18
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pyEPR-quantum==0.8.5.2
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1650904496387/work
pylint==2.13.9
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1643496850550/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1652235407899/work
pyproj @ file:///D:/bld/pyproj_1650804164778/work
PyQt5==5.12.3
PyQt5_sip==4.19.18
PyQtChart==5.12
PyQtWebEngine==5.12.1
pyrsistent @ file:///D:/bld/pyrsistent_1649013512562/work
PySocks @ file:///D:/bld/pysocks_1648857426124/work
pytest==7.1.2
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1647961439546/work
pywin32==303
pywinpty @ file:///D:/bld/pywinpty_1649088350877/work/target/wheels/pywinpty-2.0.5-cp310-none-win_amd64.whl
pyzmq @ file:///D:/bld/pyzmq_1652965558235/work
-e git+ssh://git@github.com/Qiskit/qiskit-metal.git@b0df4cdfc60af4e04c84ea2fdb456db6cc27b6dc#egg=qiskit_metal
qiskit-sphinx-theme==1.8.7
qtconsole @ file:///home/conda/feedstock_root/build_artifacts/qtconsole-base_1653414585194/work
QtPy @ file:///home/conda/feedstock_root/build_artifacts/qtpy_1651524593465/work
qutip==4.7.0
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1641580202195/work
rpyc==5.0.1
Rtree @ file:///D:/bld/rtree_1649367817754/work
scikit-learn @ file:///D:/bld/scikit-learn_1652976942320/work
scipy @ file:///C:/bld/scipy_1653074056978/work
scqubits @ file:///D:/bld/scqubits_1652478745928/work
seaborn @ file:///home/conda/feedstock_root/build_artifacts/seaborn-split_1629095986539/work
Send2Trash @ file:///home/conda/feedstock_root/build_artifacts/send2trash_1628511208346/work
Shapely==1.8.2
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
sniffio==1.2.0
snowballstemmer @ file:///home/conda/feedstock_root/build_artifacts/snowballstemmer_1637143057757/work
soupsieve @ file:///home/conda/feedstock_root/build_artifacts/soupsieve_1638550740809/work
Sphinx @ file:///home/conda/feedstock_root/build_artifacts/sphinx_1653904692612/work
sphinx-automodapi==0.14.1
sphinx-rtd-theme @ file:///home/conda/feedstock_root/build_artifacts/sphinx_rtd_theme_1617698677674/work
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-htmlhelp_1621704829796/work
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-serializinghtml_1649380998999/work
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1644872665635/work
statsmodels @ file:///D:/bld/statsmodels_1644535944524/work
sympy @ file:///D:/bld/sympy_1647802833311/work
terminado @ file:///D:/bld/terminado_1652790796353/work
threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1643647933166/work
tinycss2 @ file:///home/conda/feedstock_root/build_artifacts/tinycss2_1637612658783/work
tomli==2.0.1
tornado @ file:///D:/bld/tornado_1648827438424/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1649051611147/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1652735690480/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1650370875435/work
unicodedata2 @ file:///D:/bld/unicodedata2_1649112137711/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1647489083693/work
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1600965781394/work
webencodings==0.5.1
websocket-client==1.3.2
widgetsnbextension @ file:///D:/bld/widgetsnbextension_1647447176344/work
win-inet-pton @ file:///D:/bld/win_inet_pton_1648771897787/work
wrapt==1.14.1
xarray @ file:///home/conda/feedstock_root/build_artifacts/xarray_1646254587173/work
xyzservices @ file:///home/conda/feedstock_root/build_artifacts/xyzservices_1649934406482/work
yapf==0.32.0
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1649012893348/work

**Comment by Samuelopez-ansys** [comment]
Hi @priti-ashvin-shah-ibm ,

Could you share a small piece of code to reproduce the issue?

Thanks!

**Comment by maxcapodi78** [comment]
@priti-ashvin-shah-ibm you are correct. that is a behaviour of the native AEDT API and we cannot much. I'll investigate if I can find a trick to understand the thicken direction

**Comment by priti-ashvin-shah-ibm** [comment]
Let's see if we can get a working solution that I can use.  Since Qiskit Metal is not determining the polyline, I could determine the normal each time there is a polyline.

How about:
Is there a way for pyaedt to tell user the direction of normal for a polyline?   Seems like the information may already be stored in pyaedt, could you provide method to access it? 

or 
Make a subclass  method to create_polyline with an absolute z value to thicken to, ask opposed to a thickness value?

or 

Make a new method create_custom_3d_shape

**Comment by maxcapodi78** [comment]
@priti-ashvin-shah-ibm  you have a property in faces that gives you the normal. you could use that one to identify the direction and then use thicken sheet accordingly.

```
>>> 
m3d
<Maxwell3d object at 0x0000000000000089>
>>> m3d.modeler.object_names
['Polyline1', 'Polyline2']
>>> m3d.modeler["Polyline1"].faces[0].normal
[0.0, -0.0, -1.0]
>>> m3d.modeler["Polyline2"].faces[0].normal
[-0.0, 0.0, 1.0]
>>> 
```

**Comment by priti-ashvin-shah-ibm** [comment]
That is helpful, thank you!  For future pyaedt community, someone may want to add that information to the documentation for thicken_sheet.
