### ISSUE TITLE
Add ExportNetworkData in Q3d.post

### ISSUE THREAD

**Issue by linmingchih** [pyansys/pyaedt#1402]
### Description of the feature

I can't find the network and equivalent circuit export in Q3D.post:

![image](https://user-images.githubusercontent.com/13580731/179380100-3f4193f0-7ad6-40e1-9464-bf176edfc1b6.png)

**Comment by Samuelopez-ansys** [comment]
Hi @gmalinve ,

I think you implemented this feature recently right?

Please if I am right, could you specify where is the method to @linmingchih and close the issue?

Thanks!

**Comment by gmalinve** [comment]
Hi @Samuelopez-ansys,

I implemented the ExportMatrixData to export RLCG matrix. I didn't do anything about the export of the equivalent circuit, I shuold check.

**Comment by gmalinve** [comment]
Hi @Samuelopez-ansys , @linmingchih ,

so the export RLCG matrix data has been implemented in a previous PR (#1565 ) but the export equivalent circuit no. 
It's a completely different feature. 
Should we open a new issue to implement the export equivalent circuit and close this one?

**Comment by gmalinve** [comment]
@linmingchih 
we keep this issue to develop the export equivalent circuit feature. 
I'll assign to myself!
