### ISSUE TITLE
Add support for additional features to EDB SimulationConfiguration

### ISSUE THREAD

**Issue by isaacansys** [pyansys/pyaedt#1409]
Please expose the following settings via the EDB SimulationConfiguration and allow setting them using [configure_hfss_analysis_setup](https://github.com/pyansys/pyaedt/blob/c3fb3b138392a0f8368249bed3934be45aa84c72/pyaedt/edb_core/hfss.py#L870)

- HFSSSimulationSettings.InitialMeshSettings.MeshSizefactor [sic]
- HFSSSimulationSettings.InitialMeshSettings.UseDefaultLambda (must be False if MeshSizefactor will be set)

**Comment by svandenb-dev** [comment]
Done
