### ISSUE TITLE
Layer property change changes layer collection mode

### ISSUE THREAD

**Issue by isaacansys** [pyansys/pyaedt#1412]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Setting the roughness_enabled property on a layer changes the layer collection's mode from overlapping to laminate.

### Steps To Reproduce

Run [test_111_retain_stackup_mode](https://github.com/pyansys/pyaedt/blob/bd1a4ddf811268184735d49220ad5b68c8fe2719/_unittest/test_00_EDB.py#L1674) in [bug/stackup-mode-change](https://github.com/pyansys/pyaedt/tree/bug/stackup-mode-change).

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.9

### Installed packages

aiohttp==3.8.1
aiosignal==1.2.0
anyio==3.5.0
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
async-timeout==4.0.2        
atomicwrites==1.4.0
attrs==21.4.0
Babel==2.10.1
backcall==0.2.0
beautifulsoup4==4.11.1
black==22.1.0
bleach==5.0.0
certifi==2021.10.8
cffi==1.15.0
cfgv==3.3.1
charset-normalizer==2.0.12
click==8.1.2
codecov==2.1.12
codespell==2.1.0
colorama==0.4.4
coverage==6.3.2
cycler==0.11.0
debugpy==1.6.0
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.4
entrypoints==0.4
executing==0.8.3
fastjsonschema==2.15.3
filelock==3.6.0
flake8==3.9.2
fonttools==4.32.0
frozenlist==1.3.0
identify==2.4.12
idna==3.3
imageio==2.16.2
importlib-metadata==4.11.3
iniconfig==1.1.1
ipykernel==6.13.0
ipython==8.2.0
ipython-genutils==0.2.0
ipywidgets==7.7.0
jedi==0.18.1
Jinja2==3.1.2
json5==0.9.6
jsonschema==4.4.0
jupyter==1.0.0
jupyter-client==7.3.0
jupyter-console==6.4.3
jupyter-core==4.10.0
jupyter-server==1.17.0
jupyterlab==3.4.0
jupyterlab-pygments==0.2.2
jupyterlab-server==2.13.0
jupyterlab-widgets==1.1.0
kiwisolver==1.4.2
MarkupSafe==2.1.1
matplotlib==3.5.1
matplotlib-inline==0.1.3
mccabe==0.6.1
mistune==0.8.4
multidict==6.0.2
mypy-extensions==0.4.3
nbclassic==0.3.7
nbclient==0.6.2
nbconvert==6.5.0
nbformat==5.4.0
nest-asyncio==1.5.5
nodeenv==1.6.0
notebook==6.4.11
notebook-shim==0.1.0
numpy==1.22.3
packaging==21.3
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.9.0
pickleshare==0.7.5
Pillow==9.1.0
platformdirs==2.5.1
pluggy==1.0.0
plumbum==1.7.2
pre-commit==2.18.1
prometheus-client==0.14.1
prompt-toolkit==3.0.29
psutil==5.9.0
pure-eval==0.2.2
py==1.11.0
-e git+https://github.com/pyansys/pyaedt.git@bd1a4ddf811268184735d49220ad5b68c8fe2719#egg=pyaedt
pycodestyle==2.7.0
pycparser==2.21
pyflakes==2.3.1
Pygments==2.11.2
pyparsing==3.0.8
pyrsistent==0.18.1
pytest==7.0.0
pytest-cov==3.0.0
python-dateutil==2.8.2
pythonnet==2.5.2
pytz==2022.1
pyvista==0.34.1
pywin32==303
pywinpty==2.0.5
PyYAML==6.0
pyzmq==22.3.0
qtconsole==5.3.0
QtPy==2.1.0
requests==2.27.1
rpyc==5.0.1
scooby==0.5.12
Send2Trash==1.8.0
six==1.16.0
sniffio==1.2.0
soupsieve==2.3.2.post1
stack-data==0.2.0
terminado==0.13.3
tinycss2==1.1.1
toml==0.10.2
tomli==2.0.1
tornado==6.1
traitlets==5.1.1
typing_extensions==4.1.1
urllib3==1.26.9
virtualenv==20.14.1
vtk==9.1.0
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.3.2
widgetsnbextension==3.6.0
wslink==1.5.3
yarl==1.7.2
zipp==3.8.0

**Comment by svandenb-dev** [comment]
@isaacansys fixed
