### ISSUE TITLE
Bug located in add_siwave_syz_analysis

### ISSUE THREAD

**Issue by ring630** [pyansys/pyaedt#1441]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Sweep type only supports two types - log scale and linear count. I did below test

sweep_type = 0, it gives me linear count
sweep_type = 1, it gives me log scale
sweep_type = 2, it gives me linear count
sweep_type = 3, it gives me linear count

https://github.com/pyansys/pyaedt/blob/c486601d3a58198964e9e44c878d3302211f4db9/pyaedt/edb_core/siwave.py#L1057-L1066

when sweep_type = 1, stop_freq = 10GHz, I got below result. Why the last point is higher than 10GHz?
<img width="400" alt="image" src="https://user-images.githubusercontent.com/27995305/180385624-e1dbfffb-9e4a-4063-af37-56147223c597.png">
<img width="379" alt="image" src="https://user-images.githubusercontent.com/27995305/180384883-ae4e10aa-2ed2-40e0-bbf5-fa702ba6586f.png">

### Steps To Reproduce

```
edbapp.core_siwave.add_siwave_syz_analysis(sweeptype=1,
                                           decade_count=5,
                                           start_freq="50MHz",
                                           stop_freq="10GHz",
                                           step_freq="50MHz")
```

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

aiohttp==3.8.1
aiosignal==1.2.0
appdirs==1.4.4
async-timeout==4.0.2
attrs==21.4.0
Bottleneck @ file:///C:/Windows/Temp/abs_3198ca53-903d-42fd-87b4-03e6d03a8381yfwsuve8/croots/recipe/bottleneck_1657175565403/work
certifi @ file:///C:/Windows/TEMP/abs_e9b7158a-aa56-4a5b-87b6-c00d295b01fanefpc8_o/croots/recipe/certifi_1655968940823/work/certifi
cffi==1.15.1
charset-normalizer==2.1.0
clr-loader==0.1.7
cycler==0.11.0
fonttools==4.34.4
frozenlist==1.3.0
idna==3.3
imageio==2.19.5
kiwisolver==1.4.4
matplotlib==3.5.2
mkl-fft==1.3.1
mkl-random @ file:///C:/ci_310/mkl_random_1643050563308/work
mkl-service==2.4.0
multidict==6.0.2
networkx @ file:///C:/ci/networkx_1657716953747/work
numexpr @ file:///C:/Windows/Temp/abs_e2036a32-9fe9-47f3-a04c-dbb1c232ba4b334exiur/croots/recipe/numexpr_1656940304835/work
numpy @ file:///C:/ci/numpy_and_numpy_base_1652784037925/work
packaging @ file:///tmp/build/80754af9/packaging_1637314298585/work
pandas @ file:///C:/ci/pandas_1657532013603/work
Pillow==9.2.0
psutil @ file:///C:/Windows/Temp/abs_b2c2fd7f-9fd5-4756-95ea-8aed74d0039flsd9qufz/croots/recipe/psutil_1656431277748/work
pycparser==2.21
pyparsing @ file:///tmp/build/80754af9/pyparsing_1635766073266/work
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
pythonnet==3.0.0rc4
pytz @ file:///C:/Windows/TEMP/abs_90eacd4e-8eff-491e-b26e-f707eba2cbe1ujvbhqz1/croots/recipe/pytz_1654762631027/work
pyvista==0.35.2
pywin32==302
scooby==0.5.12
six @ file:///tmp/build/80754af9/six_1644875935023/work
vtk==9.2.0rc1
wincertstore==0.2
wslink==1.6.6
yarl==1.7.2

**Comment by Samuelopez-ansys** [comment]
@svandenb-dev Is this bug fixed?
