### ISSUE TITLE
Add the ability to calculate electric energy with PostProcessor.get_scalar_field_value()

### ISSUE THREAD

**Issue by obrienpja** [pyansys/pyaedt#1446]
### Description of the feature

In our software, [pyEPR](https://github.com/zlatko-minev/pyEPR), we calculate the electric and magnetic energy of various components in our designs. Here is an example of what the stack looks like when we evaluate the electric energy:
```
Integrate(Volume(main), Real(Dot(epsi*(<Ex,Ey,Ez>), Conj(<Ex,Ey,Ez>))))
```
In pyEPR, we add epsi*() onto the stack in the following way:
```
stack = self.stack + [("ClcMaterial", ("Permittivity (epsi)", "mult"))]
```
I do not see a way to multiply by the permittivity. I also do not see a way to calculate more complicated expressions like the one shown above (real part of the dot product between the conjugate of the E field with the product of the permittivity and the E field). Lastly, I see that volume is hard-coded to "AllObjects", and we would need to specify the volume of integration. (I can open another issue for this if you would like.)

Thank you so much for all of your hard work!

### Steps for implementing the feature

1) Allow user to specify operations that multiply by material properties like permittivity
2) Allow user to specify more complicated integrands
3) Allow user to specify volume of integration

**Comment by maxcapodi78** [comment]
Hi @obrienpja 
For complex formulas you can use directly the equations writer in pyaedt like in the following example:

`
m3d.post.ofieldsreporter.EnterScalarFunc("X")
m3d.post.ofieldsreporter.EnterVol(magnet.name)
m3d.post.ofieldsreporter.CalcOp("Mean")
m3d.post.ofieldsreporter.AddNamedExpression("CM_X", "Fields")
m3d.post.ofieldsreporter.EnterScalarFunc("Y")
m3d.post.ofieldsreporter.EnterVol(magnet.name)
m3d.post.ofieldsreporter.CalcOp("Mean")
m3d.post.ofieldsreporter.AddNamedExpression("CM_Y", "Fields")
m3d.post.ofieldsreporter.EnterScalarFunc("Z")
m3d.post.ofieldsreporter.EnterVol(magnet.name)
m3d.post.ofieldsreporter.CalcOp("Mean")
m3d.post.ofieldsreporter.AddNamedExpression("CM_Z", "Fields")
m3d.post.ofieldsreporter.CalculatorWrite(file_name, ["Solution:=", solution], variations)`

**Comment by obrienpja** [comment]
Thank you!
