### ISSUE TITLE
Add "Syntax Request" label for new issues

### ISSUE THREAD

**Issue by obrienpja** [pyansys/pyaedt#1447]
### Description of the feature

I was wondering if it would useful to have a "syntax request" label for new issues. Sometimes it seems like it should be possible for me to use pyaedt as is, but I can't figure out the syntax from the API documentation. In these cases, I could choose the "syntax request" label as opposed to the "bug" label. Just an idea. Thanks!

### Steps for implementing the feature

Create "syntax request" label for new issues (or something like that).

**Comment by MaxJPRey** [comment]
@maxcapodi78 I could add a label for "help/support".

**Comment by obrienpja** [comment]
Perfect, thank you!

**Comment by maxcapodi78** [comment]
@MaxJPRey Can you take this action? I think it is a good idea to add it to issue templates

**Comment by MaxJPRey** [comment]
@maxcapodi78 Yes, I will add this label.
