### ISSUE TITLE
Read/export R,L matrix in Maxwell3D after solution 

### ISSUE THREAD

**Issue by e-rando** [pyansys/pyaedt#1453]
### Description of the feature

A function that lets you read/export R,L matrix in Maxwell3D after solution.

**Comment by maxcapodi78** [comment]
@e-rando for which Maxwell Solution Type? Should be also applied to Maxwell2D? Can you share a small example?
@gmalinve can you take it?

**Comment by e-rando** [comment]
@gmalinve @maxcapodi78  I only use Maxwell3D with EddyCurrent, but I guess it is interesting for any of them. 
What I meant to read is this matrix (setup -> solutions -> Matrix):

![image](https://user-images.githubusercontent.com/109361037/181766343-1cfd34f8-71f1-4804-b2e2-ac0697b40a20.png)


For my application, it is very relevant to be able to access not only to 'Reduce matrix: original', but also to the matrices generated with the matrix reduction (join in parallel/series)

In my opinion, the most useful way to acquire this data is with a list or a list of lists that contain the parameters. Probably two different outputs, one for R and one for L would be best.

**Comment by gmalinve** [comment]
Hi @e-rando , would you have a ready-made example so I can understand better what you intend to do please? 
Maybe an example with the reduced matrix and the ones generated with matrix reduction.
thanks!

**Comment by gmalinve** [comment]
Hi @e-rando . I have implemented the requested feature for Maxwell 2D and 3D, PR is created and waiting for approval!
