### ISSUE TITLE
Get basis frequencies in interpolating frequency sweeps

### ISSUE THREAD

**Issue by pgurrala19** [pyansys/pyaedt#1458]
### Description of the feature

Methods for exporting field solutions, such as [PostProcessor.export_field_file](https://github.com/pyansys/pyaedt/blob/7093181cb27a2cc780fff85c9a64a69b523268de/pyaedt/modules/PostProcessor.py#L2324), require an intrinsics parameter that specifies the frequency at which the fields are calculated. To export the field solution at each frequency in a discrete frequency sweep, one can get a list of frequencies from SolutionData.instrinsics and run a for loop. 

This does not work for an interpolating frequency sweep because SolutionData.instrinsics has all frequencies in the definition of the sweep, whereas field solutions are available only at the basis frequencies. There needs to be a way to get only the interpolation basis frequencies, for example, through a new attribute in [SolutionData](https://github.com/pyansys/pyaedt/blob/7093181cb27a2cc780fff85c9a64a69b523268de/pyaedt/modules/solutions.py#L43).

**Comment by maxcapodi78** [comment]
@pgurrala19 I've implemented in #1474
now Sweep has  properties: frequencies and basis_frequencies.

Example

```
hfss.setups[0].sweeps[0].basis_frequencies
hfss.setups[0].sweeps[0].frequencies

```

This methods works ONLY if solutions are present and project is saved as it is reading solution folder
