### ISSUE TITLE
EDB: Allow padstack plating thickness to be changed 

### ISSUE THREAD

**Issue by Jan-Hammer** [pyansys/pyaedt#1468]
### Description of the feature

pyaedt.edb_core.EDB_Data.EDBPadstack Via plating attribute

EDBPadstack.hole_plating_thickness

is read-only. 
Please add function to change the plating thickness of padstacks

### Steps for implementing the feature

Either create a new setter function or adjust 
EdbPadstacks.set_pad_property

**Comment by maxcapodi78** [comment]
Implemented
