### ISSUE TITLE
edb export via SiWave execute GUI-less 

### ISSUE THREAD

**Issue by Jan-Hammer** [pyansys/pyaedt#1477]
### Description of the feature

Exporting from EDB via SiWave would benefit from a flag that allows the operation to be performed without the GUI opening

**Comment by maxcapodi78** [comment]
Siwave doesn't have a proper way to run script in non graphical. BTW I'm adding a bool argument to export_maxwell named hidden which runs Siwave in embedding mode. It means you will see siwave icon but not the UI
