### ISSUE TITLE
Add Assign Current Density and Assign Current Density Terminal in Maxwell 3D

### ISSUE THREAD

**Issue by JuliusSaitz** [pyansys/pyaedt#1489]
### Description of the feature

Current Density is an excitation type that is sometimes needed, if the current density is known instead of current. Current Density Terminal needs to be specified, if Current Density excitation type is used. This is applicable to Magnetostatic and Eddy Current designs.

### Steps for implementing the feature

Implementation of existing APIs:

oModule = oDesign.GetModule("BoundarySetup")

oModule.AssignCurrentDensity(
	[
		"NAME:CurrentDensity1",
		"Objects:="		, ["NewObject_45UOWT"],
		"Phase:="		, "0deg",
		"CurrentDensityX:="	, "0",
		"CurrentDensityY:="	, "0",
		"CurrentDensityZ:="	, "1",
		"CoordinateSystem Name:=", "Global",
		"CoordinateSystem Type:=", "Cartesian"
	])

"Phase" is applicable in Eddy Current design only.

oModule.AssignCurrentDensityTerminal(
	[
		"NAME:CurrentDensityTeminal1",
		"Faces:="		, [35]
	])

**Comment by Samuelopez-ansys** [comment]
Please @gmalinve could you check this issue?
