### ISSUE TITLE
Bug located in modeler/Object3d.Padstack

### ISSUE THREAD

**Issue by schang412** [pyansys/pyaedt#1493]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

When attempting to create a padstack using Object3d.Padstack and attempting to use the padstack in via creation for hfss3dlayout, the padstack layers are unable to be assigned to the via layers. 

This may be attributed to the id value in pads_args being a string instead of number. When the padstack is created manually and the automation is recorded, id is set to a number (i.e. `'id:=', 1,`). However, calling `my_padstack.pads_args()` on the code below will show  `'id:=', 'L1',`

### Steps To Reproduce

After running the following code to setup the Hfss3dLayout session, creating the padstack and associated via:
```python
from pyaedt import Hfss3dLayout

h3d = Hfss3dLayout("2022.2", non_graphical=False, new_desktop_session=True)
h3d.modeler.layers.add_layer(
   layername="L2",
   layertype="signal",
   thickness="0.5mm",
   isnegative=False,
   material="copper",
   elevation=0
)
h3d.modeler.layers.add_layer(
   layername="D12",
   layertype="dielectric",
   thickness="0.5mm",
   isnegative=False,
   material="FR4_epoxy",
   elevation=0.5
)
h3d.modeler.layers.add_layer(
   layername="L1",
   layertype="signal",
   thickness="0.5mm",
   isnegative=False,
   material="copper",
   elevation=1.0
)
my_padstack = h3d.modeler.new_padstack("my_padstack")
my_padstack.hole = my_padstack.add_hole(
    holetype="No",
    sizes=[],
    xpos="0mm",
    ypos="0mm",
    rot="0deg",
)
my_padstack.add_layer(
   layername="L1",
   pad_hole=my_padstack.add_hole("Cir", ["10mm"], "0um", "0um", "0deg")
)
my_padstack.create()

h3d.modeler.create_via(
   padstack="my_padstack",
   x=0,
   y=0,
   hole_diam=None,
   top_layer="L1",
   bot_layer="L1",
   name="my_via",
   netname="GND"
)
```
At this point, a via is created inside Hfss3dLayout with the padstack, but there is no pad visually in the viewer. On inspection of the padstack usage of the via, L1's padstack is set to None. The "L1" padstack is available as an option in the combobox, but I am unable to select it. Clicking "Ok" will reset the text back to None. 

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

aiohttp==3.8.1
aiosignal==1.2.0
anyio==3.6.1
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
async-timeout==4.0.2
attrs==21.4.0
Babel==2.10.3
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.1
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.1.0
clr-loader==0.1.7
colorama==0.4.5
cycler==0.11.0
debugpy==1.6.2
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.4
executing==0.8.3
fastjsonschema==2.15.3
fonttools==4.34.4
frozenlist==1.3.0
idna==3.3
imageio==2.19.3
ipykernel==6.15.1
ipython==8.4.0
ipython-genutils==0.2.0
jedi==0.18.1
Jinja2==3.1.2
json5==0.9.8
jsonschema==4.7.1
jupyter-client==7.3.4
jupyter-core==4.11.1
jupyter-server==1.18.1
jupyterlab==3.4.3
jupyterlab-pygments==0.2.2
jupyterlab-server==2.15.0
kiwisolver==1.4.3
MarkupSafe==2.1.1
matplotlib==3.5.2
matplotlib-inline==0.1.3
mistune==0.8.4
multidict==6.0.2
nbclassic==0.4.2
nbclient==0.6.6
nbconvert==6.5.0
nbformat==5.4.0
nest-asyncio==1.5.5
notebook-shim==0.1.0
numpy==1.23.1
packaging==21.3
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
Pillow==9.2.0
plumbum==1.7.2
prometheus-client==0.14.1
prompt-toolkit==3.0.30
psutil==5.9.1
pure-eval==0.2.2
pyaedt==0.5.1
pycparser==2.21
pydantic==1.9.1
Pygments==2.12.0
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
pythonnet==3.0.0rc2
pytz==2022.1
pyvista==0.35.1
pywin32==304
pywinpty==2.0.6
pyzmq==23.2.0
requests==2.28.1
rpyc==5.0.1
scooby==0.5.12
Send2Trash==1.8.0
six==1.16.0
sniffio==1.2.0
soupsieve==2.3.2.post1
stack-data==0.3.0
terminado==0.15.0
tinycss2==1.1.1
tornado==6.2
traitlets==5.3.0
typing_extensions==4.3.0
urllib3==1.26.10
vtk==9.2.0rc1
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.3.3
wslink==1.6.6
yarl==1.7.2

**Comment by maxcapodi78** [comment]
I've fixed in #1626
