### ISSUE TITLE
#1469 still present in 0.5.20

### ISSUE THREAD

**Issue by Jan-Hammer** [pyansys/pyaedt#1508]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Bug #1469 is still present

### Steps To Reproduce

see #1469

### Which Operating System are you using?

Linux

### Which Python version are you using?

3.9

### Installed packages

see #1469

**Comment by maxcapodi78** [comment]
@Jan-Hammer I've fixed it. There was a typo error in my previous implementation that was causing it working on the unclassified creation but not in the refresh (your usecase).
