### ISSUE TITLE
random characters appear in Voltage/Current source names

### ISSUE THREAD

**Issue by skandak-ansys** [pyansys/pyaedt#1513]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

When using **SimulationConfiguration** object, if I add voltage or current sources, the names of the sources get appended by random characters after running the script.

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/98126702/183125017-8e01f70a-113c-496e-b8de-2daba8239f31.png)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.9

### Installed packages

pyaedt

**Comment by maxcapodi78** [comment]
#1581
