### ISSUE TITLE
Add ability to edit stackup layer name in EDB

### ISSUE THREAD

**Issue by skandak-ansys** [pyansys/pyaedt#1518]
### Description of the feature

![image](https://user-images.githubusercontent.com/98126702/183469489-6ba95ea0-58f3-4e97-bec1-96edc07a2baf.png)

Here, `pyaedt `allows users to change all properties associated with a specific layer. However, it doesn't allow users to change layer name. 

It is a useful feature to have the ability to change the layer name.

### Steps for implementing the feature

See pic above.

**Comment by skandak-ansys** [comment]
cc - @mahesh-dhanekula

**Comment by Samuelopez-ansys** [comment]
@skandak-ansys is this feature already merged?

If it is, please could you close the issue?

Thank you

**Comment by mahesh-dhanekula** [comment]
@Samuelopez-ansys 

Let me create the pull request for this feature, will request review from you.

**Comment by pyAnsysUser** [comment]
my understanding is this functionality is included in EDBLayer.update_layer_vals() ? The documentation here is not very precise.

**Comment by mahesh-dhanekula** [comment]
@pyAnsysUser 
Except for the name everything can be modified in layer attributes

**Comment by pyAnsysUser** [comment]
This might be the right way to go, but #1064 may point to a logical bug located in the layer properties when adding a layer. I am still working my way through the code that sets the new id value for the added layer.

**Comment by SHF101202021** [comment]
@pyAnsysUser 
Thanks for you replies
After figuring out some solutions for #1064,  I think the proposed method here would not happen like you thought

**Comment by mahesh-dhanekula** [comment]
@pyAnsysUser 
Seems like this solution is failing on my end if I tried to modify the layer name second time. Can you confirm by verifying this behavior ?

**Comment by Samuelopez-ansys** [comment]
@svandenb-dev please could you check this issue? Thanks!

**Comment by ring630** [comment]
@Samuelopez-ansys @SHF101202021 @mahesh-dhanekula @pyAnsysUser @skandak-ansys please use the new stackup method to change layer name.

`edbapp.stackup["TOP"].name = "new_name"`

Below is another example
https://github.com/pyansys/pyaedt/blob/7707a8875584270ed1c304e80be416b29d45f4b4/_unittest/test_00_EDB.py#L2036-L2046
