### ISSUE TITLE
how can we change port_name

### ISSUE THREAD

**Issue by kclme84** [pyansys/pyaedt#1557]
### Description of the feature

if we use h3d.create_edge_port("microstrip",0) to create one edge port ,how can we change this port name? thanks !

**Comment by ring630** [comment]
@kclme84 changing property in aedt is not impossible, but cumbersome. I highly recommend to assign the correct port name in the first place.

**Comment by ring630** [comment]
@kclme84, aedt is only intended to create. I am investigating if port can be created in EDB in which changing its properties is much more convenient.

**Comment by kclme84** [comment]
@ring630 ok,thanks ! I will be trying!

**Comment by kclme84** [comment]
we can use "Modeler3DLayout.change_property()" to modify the port name.thanks!
@ring630
