### ISSUE TITLE
Add the option of "Convex Hull" in the argument of extent_type in the method create_cutout()

### ISSUE THREAD

**Issue by SHF101202021** [pyansys/pyaedt#1562]
### Description of the feature

In HFSS 3D Layout, one expansion type of the cutout regions is "convex hull"
![image](https://user-images.githubusercontent.com/88426850/185573667-061692ee-e034-467a-9ae5-25372e530a70.png)

I want to request if this option can be added in ```Edb.create_coutout()``` or not
Though in ```Ansys.Ansoft.EDB.Geometry```, only ```BoundingBox``` and ```Conforming``` are available...
![image](https://user-images.githubusercontent.com/88426850/185574574-ff4d15c9-686c-4feb-ac74-e663eb242570.png)

### Useful links and references

Assume Ansys EM software is installed in your computer
Manual Location->   ```C:\Program Files\AnsysEM\v222\Win64\Help\Edb\Documentation.chm```

**Comment by ring630** [comment]
@SHF101202021 If Convex Hull is not in Edb.Geometry, we cannot have it in PyAEDT.

**Comment by ring630** [comment]
@svandenb-dev , is it possible any enhancement can be done in EDB.dll?

**Comment by ring630** [comment]
@SHF101202021 I consider it as a limitation because it cannot be improved from pyaedt side. If it is ok, I will close this issue.

**Comment by SHF101202021** [comment]
Ok. Please close this issue
Thank for your replies

**Comment by ring630** [comment]
@SHF101202021 very interesting. I did some test but failed. HFSSExtentInfoType is not accepted by GetExpandedExtentFromNets. HFSSExtentInfoType is for other purposes. ConvexHull support as ExtentType needs to be implemented in Edb.dll. Let me discuss it internally.

**Comment by SHF101202021** [comment]
@ring630 
Just share my idea:

Noted: ```aedb``` -> ![image](https://user-images.githubusercontent.com/88426850/186114692-e3457c2d-14c0-4662-a2ad-d4f71df36def.png)


Before actually cutting out, one needs to define the polygon for the regions
![image](https://user-images.githubusercontent.com/88426850/186112603-c2080ffe-f1d7-4832-93eb-1529821d1ce9.png)

Then, turn this polgon to be ```IList<PolyData>``` and implement ```Ansys.Ansoft.Geometry.PolygonData.GetConvexHullOfPolygons()``` like the following
![image](https://user-images.githubusercontent.com/88426850/186113337-4c0355a2-1527-41af-ac42-2e5b2e1c5fa4.png)

It can pass eventually, however the arc data is missing: 
#### Polygon generated by ```GetExpandedExtentFromNets```
##### Code 
![image](https://user-images.githubusercontent.com/88426850/186114347-19ed709f-e0f1-43c3-a8d4-9c29d9a5f87b.png)
##### Shape
![image](https://user-images.githubusercontent.com/88426850/186115334-3246353f-d691-457a-af2e-e669405acff0.png)


#### Polgygon transformed by ```GetConvexHullOfPolygons```
##### Code 
![image](https://user-images.githubusercontent.com/88426850/186114396-44d993eb-9247-430f-8501-b0d60fe4ee16.png)
##### Shape
![image](https://user-images.githubusercontent.com/88426850/186115433-34fccd6f-eca3-480e-a1be-81475a5d913d.png)

> If just observing the new shape, it is really convex hull, but without arc line if one save the data and see in 3DLayout.


### In 3D Layout

Here are the cut layout showed in 3D Layout

#### Cutout with ```GetConvexHullOfPolygons```
![image](https://user-images.githubusercontent.com/88426850/186116255-be4b0ef3-e017-4707-b9cb-0f2000acf0d1.png)

#### Cutout with 3DLayout Cutout GUI
![image](https://user-images.githubusercontent.com/88426850/186116571-aba67d7f-8b09-4237-a192-646bf81e2a34.png)

**Comment by SHF101202021** [comment]
> @SHF101202021 very interesting. I did some test but failed. HFSSExtentInfoType is not accepted by GetExpandedExtentFromNets. HFSSExtentInfoType is for other purposes. ConvexHull support as ExtentType needs to be implemented in Edb.dll. Let me discuss it internally.

@ring630  
Ansys had ever publish a tool called 'PinToPin.exe'
Maybe you can refer codes in Ansys internal Libraray
 as the guidance for this issue ![image](https://user-images.githubusercontent.com/88426850/186277613-81ceaf0d-0588-4a9a-a138-4428df0ba03e.png)

**Comment by SHF101202021** [comment]
@ring630  
Got your point. 
Wait for your news for ConvexHull :D

**Comment by ring630** [comment]
@SHF101202021 convex hull is implemented as you suggested. The generated extent is not exactly the same as it is from GUI, but I think it is acceptable.
![image](https://user-images.githubusercontent.com/27995305/186609310-68f28cea-8a23-4e11-beee-09d3d96c36d3.png)

**Comment by SHF101202021** [comment]
@ring630 
Thanks for your trying!
