### ISSUE TITLE
Add more features to HFSS 3D Layout stackup editor module

### ISSUE THREAD

**Issue by Marcel0000** [pyansys/pyaedt#1592]
### Description of the feature

It would be nice, if the methods & attributes available in `pyaedt.edb_core.EDB_Data.EDBLayer` would be implemented in `pyaedt.modules.LayerStackup.Layer` as well for usage directly in HFSS 3D Layout.
E.g. change name, thickness, roughness etc.

### Useful links and references

[https://aedt.docs.pyansys.com/API/_autosummary/pyaedt.modules.LayerStackup.Layer.html](https://aedt.docs.pyansys.com/API/_autosummary/pyaedt.modules.LayerStackup.Layer.html)

[https://aedt.docs.pyansys.com/API/_autosummary/pyaedt.edb_core.EDB_Data.EDBLayer.html](https://aedt.docs.pyansys.com/API/_autosummary/pyaedt.edb_core.EDB_Data.EDBLayer.html)

**Comment by maxcapodi78** [comment]
@Marcel0000 I'll check and add this enhancement. 
Anyway you can combine both tools to obtain what you need. 

First open the aedb folder with Edb class and do all modifications
Then open the aedb folder with Hfss3dLayout to run analysis and postprocessing
