### ISSUE TITLE
How to get port reference objects ?

### ISSUE THREAD

**Issue by kclme84** [pyansys/pyaedt#1593]
### Description of the feature

if one has two reference objects,how can we get all of them ? Then I will choose one of them to set the real reference .Thanks!

![1](https://user-images.githubusercontent.com/41882604/186542493-37e9fe88-a727-4fc4-a8ff-c62b84a87e98.jpg)

**Comment by maxcapodi78** [comment]
@kclme84  I've implemented a new class containing all ports info for Hfss3dLayout. this is returned automatically when you create a port is created with pyaedt or read in h3d.boundaries list of objects when you read it from an existing project. the new class has also getters and setters so you can for instance change the reference directly from it.

example
```
h3d = Hfss3dLayout()
h3d.boundaries[0]["Reference"] = "Bottom:poly_756"

```
