### ISSUE TITLE
Allow assignment of corresponding properties Laminations for Maxwell 2D/3D

### ISSUE THREAD

**Issue by emmridi** [pyansys/pyaedt#1608]
### Description of the feature

As extension to #1512 which introduced the stacking type for Maxwell materials it should also be possible to set (and get from AEDT materials) the stacking direction and stacking factor for stacking_type="Lamination"

**Comment by POWER-TRANSFORMER** [comment]
Do u know how to assign composition(stacking_type) in EddyCurrent 2D?
mat_core.stacking_type="Lamination" not work.

**Comment by Samuelopez-ansys** [comment]
@gmalinve If you have time, could you check this issue?

Thanks!

**Comment by MaxJPRey** [comment]
@Samuelopez-ansys @gmalinve I will fix it.
