### ISSUE TITLE
Consider moving jupyterlab out of install_requires

### ISSUE THREAD

**Issue by isaacansys** [pyansys/pyaedt#1628]
### Description of the feature

Jupyter Lab and its dependencies add significant download and install weight.

### Steps for implementing the feature

If Jupyter Lab is not required except for the example ipynb files, consider moving this dependency out of setup.py install_requires and into a new requirements file like requirements-examples.txt.

**Comment by maxcapodi78** [comment]
@isaacansys I agree. I'm implementing it. I leave in pyvista, matplotlib and numpy as they are actively used in different methods
