### ISSUE TITLE
Add SIwave DCIR post processing features 

### ISSUE THREAD

**Issue by skandak-ansys** [pyansys/pyaedt#1671]
### Description of the feature

After performing DCIR simulation, there is no way for the user to extract information about Loop resistance, path resistance, RL table etc. It will be useful for the user to access these parameters through pyaedt commands.

**Comment by Samuelopez-ansys** [comment]
@ring630 What is the status of this issue?

**Comment by ring630** [comment]
@skandak-ansys new method added. 

`
hfss3d = Hfss3dLayout(self.dcir_example_project, "Galileo_G87173_204", specified_version=desktop_version)
hfss3d.get_dcir_solution_data("Siwave_DC_WP9QNY", "RL", "Path Resistance")
hfss3d.get_dcir_solution_data("Siwave_DC_WP9QNY", "Vias", "Current")

solution_data = hfss3d.get_dcir_solution_data("Siwave_DC_WP9QNY", "Sources", "Voltage")
solution_data.data_magnitude(solution_data.expressions[0])
`

**Comment by svandenb-dev** [comment]
closing the issue thanks @ring630
