### ISSUE TITLE
Add ..For Q3D, Could we have the data in a pandas dataframe, not a dict? I would need to parse the keys of the dict and build a table. It appears that the data is stored in some type of table format already. I am asking since a table may be available through pyaedt.

### ISSUE THREAD

**Issue by priti-ashvin-shah-ibm** [pyansys/pyaedt#1676]
### Description of the feature

For Q3D, Could we have the data in a pandas dataframe, not a dict? I would need to parse the keys of the dict and build a table. It appears that the data is stored in some type of table format already due to format in GUI image below. I am asking since a table may be available through pyaedt.  An alternate solution is to provide choice of format of dict? One option is to return a dict as it exists, but another option to return a dict which can be used to import into a dataframe using syntax like:  

`pd.DataFrame.from_dict(a._solution_data_real())`

Another solution would be to give numpy matrix. Just brainstorming ideas.

![image](https://user-images.githubusercontent.com/74020801/189135862-227328af-5499-4643-a48d-8bbdc890c8e5.png)

@obrienpja , @Samuelopez-ansys , @ThomasGM4

### Useful links and references

Issue https://github.com/pyansys/pyaedt/issues/1650 has helpful snippets to get a dict for solution data.
#1675, #1677

**Comment by Samuelopez-ansys** [comment]
Hi @priti-ashvin-shah-ibm ,

This request is interesting and you are not the first user asking for it. We will evaluate the best approach to integrate it because pandas are just using numpy and then it will not increase too much the package size because pyaedt is using numpy too. I will keep you updated with our developments regarding this issue.

Thanks

**Comment by Samuelopez-ansys** [comment]
@priti-ashvin-shah-ibm Hopefully PR #1700 will return the data structure you need, tomorrow it will be merged. This PR also created a public method to get all data, hopefully it will solve the issue #1675

Take a look and let us know if what you expect

**Comment by priti-ashvin-shah-ibm** [comment]
Awesome, thank you!!!
