### ISSUE TITLE
Misspelling in function expression for Primitives2D.py in Modeler

### ISSUE THREAD

**Issue by PipKat** [pyansys/pyaedt#172]
The parameter radius is misspelled in this function expression:

def create_ellipse(self,position, major_raidus, ratio, bIsCovered=True, name=None, matname=None):

**Comment by akaszynski** [comment]
Still an issue.  See:
```
./pyaedt/modeler/Primitives3D.py\0455:    def create_ellipse(self, cs_plane, position, major_raidus, ratio, is_covered=True, name=None, matname=None):
./pyaedt/modeler/Primitives3D.py\0464:        major_raidus : float
./pyaedt/modeler/Primitives3D.py\0486:        MajorRadius = self._arg_with_dim(major_raidus)
```

**Comment by MaxJPRey** [comment]
Parameters have been renamed.
Current method's signature is:
`def create_ellipse(self, position, major_radius, ratio, is_covered=True, name=None, matname=None):`

**Comment by Piwakk** [comment]
Hi,
Sorry for commenting on a closed issue, but it seems that the typo is still in main:

https://github.com/pyansys/pyaedt/blob/146680f6b2d9fc73d5f70c09cf0556cda8cd2645/pyaedt/modeler/Primitives3D.py#L565

**Comment by MaxJPRey** [comment]
> Hi, Sorry for commenting on a closed issue, but it seems that the typo is still in main:
> 
> https://github.com/pyansys/pyaedt/blob/146680f6b2d9fc73d5f70c09cf0556cda8cd2645/pyaedt/modeler/Primitives3D.py#L565

Hi Piwakk, 
Indeed the argument "major_raidus" is mispelled in Primitives3D, the title of this issue mentionned Primitives2D. That's why we have been closing it. 
Thanks for raising this issue.
I just created a new issue.
