### ISSUE TITLE
Units cannot be modified in the 3D Layout modeler.

### ISSUE THREAD

**Issue by MaxJPRey** [pyansys/pyaedt#1729]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Open the 3D Layout modeler.
Then enter the following code:

`aedtapp.modeler.model_units = "dm"`

You will see in the bottom right corner that units are not modified.

### Steps To Reproduce

N/A

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.8

### Installed packages

N/A

**Comment by maxcapodi78** [comment]
I think this is a bug of the native API. Can you submit to our Developers? @MaxJPRey
