### ISSUE TITLE
hybrid property in HFSS is not working

### ISSUE THREAD

**Issue by MaxJPRey** [pyansys/pyaedt#1730]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

```
from pyaedt import Hfss
aedtapp = Hfss()
```

Modify manually the type of solution to HFSS Hybrid.
Then enter the following code:

`aedtapp.design_solutions.hybrid`

It will always return `False`, while it should return `True`.

### Steps To Reproduce

N/A.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.8

### Installed packages

N/A

**Comment by Samuelopez-ansys** [comment]
Hi @MaxJPRey ,

Are you working on that?

We can help you to identify the issue.

**Comment by MaxJPRey** [comment]
@Samuelopez-ansys Yes I did. I will try to finish it as soon as possible.
