### ISSUE TITLE
Request for better documentation for setup_edit

### ISSUE THREAD

**Issue by arobinson905** [pyansys/pyaedt#1743]
edit_setup function in the PyAEDT website does not show the user how to edit this call
https://aedt.docs.pyansys.com/API/_autosummary/pyaedt.Hfss.edit_setup.html#pyaedt.Hfss.edit_setup

The additional information in the HFSS Scripting help setup does not use proper syntax to show how to call this function.

oModule.EditSetup("Setup1", 
["NAME:NewSetup",
"AdaptiveFreq:=", "1GHz", 
"EnableDistribProbTypeOption:=", false,
"SaveFields:=", "true", 
"Enabled:=", true, 
["NAME:Cap", 
	"MaxPass:=", 10, 
	"MinPass:=", 1, 
	"MinConvPass:=", 2, 
	"PerError:=", 1, 
	"PerRefine:=", 30, 
	"AutoIncreaseSolutionOrder:=", false, 
	"SolutionOrder:=", "Normal"],
["NAME:DC", 
	"Residual:=", 1E-005, 
	"SolveResOnly:=", false, 
	["NAME:Cond",
		"MaxPass:=", 10, 
		"MinPass:=", 1, 
		"MinConvPass:=", 1, 
		"PerError:=", 1, 
		"PerRefine:=", 30), 
	["NAME:Mult", 
		"MaxPass:=", 1, 
		"MinPass:=", 1, 
		"MinConvPass:=", 1, 
		"PerError:=", 1, 
		"PerRefine:=", 30]], 
["NAME:AC",
	"MaxPass:=", 10, 
	"MinPass:=", 1, 
	"MinConvPass:=", 2, 
	"PerError:=", 1, 
	"PerRefine:=", 30]]
)

**Comment by maxcapodi78** [comment]
@arobinson905 
the edit_setup method is there for legacy purposes. There is a new, elegant way to do it right now.
you have all your setups in setups variable and from there all the props can be get/set. You need to know the property name.

```
from pyaedt import Hfss
hfss = Hfss()
all_setups = hfss.setups   # get all setups
first_setup =all_setups[0]  
print(first_setup.name)       # get setup name
first_setup.props["MaxPass"]= 3   # change a property
```
