### ISSUE TITLE
create_rlc_component() not working for rotated components

### ISSUE THREAD

**Issue by ErikZalm** [pyansys/pyaedt#1765]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

For rotated components the create_rlc_component does not work correctly. 
The rotation is not copied from the host component and the pads are placed on the wrong location.
Changing the SetPosition/GetPosition to SetTransform/GetTransform fixes this for my (mentor expedition ODB++) designs.

### Steps To Reproduce

Read ODB++ file with rotated components (For example soic 4).
creata rlc on pins 2 and 3.
Check the EDB file with SiWave

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.8

### Installed packages

aiohttp==3.8.3
aiosignal==1.2.0
appdirs==1.4.4
async-timeout==4.0.2
attrs==22.1.0
autopep8==1.7.0
cffi==1.15.1
charset-normalizer==2.1.1
clr-loader==0.2.3
contourpy==1.0.5
cycler==0.11.0
fonttools==4.37.3
frozenlist==1.3.1
idna==3.4
imageio==2.22.0
kiwisolver==1.4.4
matplotlib==3.6.0
multidict==6.0.2
numpy==1.23.3
packaging==21.3
pandas==1.5.0
Pillow==9.2.0
pip-review==1.2.0
plumbum==1.7.2
psutil==5.9.2
pyaedt==0.6.5
pycodestyle==2.9.1
pycparser==2.21
pyparsing==3.0.9
python-dateutil==2.8.2
pythonnet==3.0.0rc6
pytz==2022.2.1
pyvista==0.36.1
pywin32==304
rpyc==5.0.1
scooby==0.6.0
six==1.16.0
toml==0.10.2
vtk==9.1.0
wslink==1.8.2
yarl==1.8.1

**Comment by svandenb-dev** [comment]
fixed currently merged in the main branch.
