### ISSUE TITLE
Numerous "Windows fatal exception: code 0x800706ba" in unit test output

### ISSUE THREAD

**Issue by myoung-ansys** [pyansys/PyAEDT#181]
At the end of the tests, after the summary line is printed, a large number of these errors are printed. This seems to happen for all tests. 

Here is the output for one very short test (test_emit.py):

![image](https://user-images.githubusercontent.com/86373761/123695984-d7711e80-d820-11eb-92cf-52066a4917e2.png)

**Comment by akaszynski** [comment]
When running local unit testing, use the option `-p no:faulthandler`.  For example:
```py
pytest _unittest -p no:faulthandler
```

This will cleanup these error messages.  This has been added to our CI as a default option in `pytest.ini`

**Comment by myoung-ansys** [comment]
The option works great - thank you!
