### ISSUE TITLE
Maxwell3D -> assign_master_slave

### ISSUE THREAD

**Issue by kutlayacar** [pyansys/pyaedt#1994]
### Description of the feature

Hello,

I couldn't find any function to set Master and Slave Boundaries in Maxwell3D like in Maxwell2D. Is there any way to do that? I unfortunately couldn't find nothing in API Documentation.

Thanks in advance!

**Comment by gmalinve** [comment]
Hi @kutlayacar .
The method to set master slave boundaries is already available in pyaedt: assign_master_slave.
Please have a look at the available examples, you can find it in the Maxwell2D Nissan Leaf example.

**Comment by kutlayacar** [comment]
Hi @gmalinve 

Thank you for your response.

I already know that, there is a method to set master slave boundaries in Maxwell2d. My question is how can I set master slave boundaries in "Maxwell3d" as in Maxwell2d.

Best,

**Comment by gmalinve** [comment]
Hi @kutlayacar ,
A PR has just been created.
Regards,
