### ISSUE TITLE
Uncheck Compute Fields in SBR+ 

### ISSUE THREAD

**Issue by Samuelopez-ansys** [pyansys/pyaedt#1998]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Detected a bug in AEDT API, it is not possible to uncheck the Compute Fields option in SBR+. This has to be fixed in Ansys Dev. side.

### Steps To Reproduce

Create Setup in SBR+
Try to uncheck Compute Fields

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.9

### Installed packages

-

**Comment by maxcapodi78** [comment]
so we can close for now from PyAEDT Backlog
