### ISSUE TITLE
Bug in showing nets in HFSS3DLayout

### ISSUE THREAD

**Issue by SHF101202021** [pyansys/pyaedt#2056]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

## Problem Statement
**The following codes will not show the whole nets**

These are my nets
![image](https://user-images.githubusercontent.com/88426850/204544070-3a394180-0211-42e9-ae3b-d33b133ec6f4.png)

Here is the code
```python

hfss = Hfss3dLayout(specified_version='2022.2', 
                    projectname='certain project',
                    designname='certain design')

# This print will not show all the nets
print(hfss.modeler.nets)

```

Here are how console shows
![image](https://user-images.githubusercontent.com/88426850/204546052-a7e4dbd2-e18d-4497-b8bd-2966735ff00e.png)

## Reason
> PyAEDT get net names by only parsing the group **<Power/Ground>** and **Non Power/Ground**

Owning to pyaedt only parsing two specific net group, the net outside the group will not be recognized
In this case, my project is generated by SIWave with ```generating hfss region options```
Eventually, the group, **Non Power/Ground** disappear for unknown reason so that I want to notice you to aviod this bug by modify sort of codes

![image](https://user-images.githubusercontent.com/88426850/204548206-04e410ae-46a7-49c4-83aa-0a5e1cc5de0b.png)

## Suggestion
When getting all nets of the design, use ```GetNets()``` instead
![image](https://user-images.githubusercontent.com/88426850/204548603-30e3c8d7-8d0e-4c49-ae35-42a7c011c8df.png)

I suggest the code can be modified as the following:

```python

@property
def nets(self):
    """Nets.

    Returns
    -------
    dict[str, :class:`pyaedt.modeler.object3dlayout.Nets3DLayout`]
        Nets Dictionary.

    """

    if self._nets:
        return self._nets

    for k, v in self.power_nets.items():
        self._nets[k] = v
    for k, v in self.signal_nets.items():
        self._nets[k] = v

    objs = self.modeler.oeditor.GetNets()
    for obj in objs:
        if obj not in self.power_nets and obj not in self.signal_nets:
            self._nets[obj] = Nets3DLayout(self, obj)
    return self._nets

```

### Steps To Reproduce

Just cancel nets in either ```<Power/Ground>``` or ```Non Power/Ground```
Here, I use  ```Non Power/Ground```

![image](https://user-images.githubusercontent.com/88426850/204575148-bb230031-989c-4268-94dc-62e36ccfb675.png)

#### Before cancelling
![image](https://user-images.githubusercontent.com/88426850/204575347-becd9f84-e6a5-4cc5-adc2-a29c585860d0.png)

#### After cancelling
![image](https://user-images.githubusercontent.com/88426850/204575422-c79e16bf-80c9-4e00-a7eb-9f55c5124c3c.png)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.9

### Installed packages

Not Important here

**Comment by SHF101202021** [comment]
I can try to push the code myself (If you had some instruction, that will be better.  If not, I can figure out myself)
But I'm not sure if I had the authority to do that

**Comment by SHF101202021** [comment]
@gmalinve 

Please check **Net Block** in AEDT
The reason you can get the ```len(nets) = len(signal_nets) + len(power_nets)``` is that you have both ```<Power/Ground>``` and ```Non Power/Ground``` Net Group

For my project, ```Non Power/Ground``` net group is missing so that my nets cannot show signal_nets
![image](https://user-images.githubusercontent.com/88426850/204573498-c21d0733-a506-483f-9c44-7e1de41e01e1.png)

**Comment by gmalinve** [comment]
Hi @SHF101202021 ,
A PR to fix this issue has just been created.
Thanks for reporting!
