### ISSUE TITLE
Use pyansys/actions in the workflow.

### ISSUE THREAD

**Issue by MaxJPRey** [pyansys/pyaedt#2071]
### Description of the feature

💡 **Idea**
With the recent release of [pyansys/actions], we could upgrade the CI/CD workflows.

In addition these actions introduced the multi-version documentation feature, meaning that we can get rid of our stable and developers doc repositories.

[pyansys/actions]: https://github.com/pyansys/actions

**Comment by PipKat** [comment]
@MaxJPRey We'd still have the "release" doc and the "in-main/production" doc though, yes?

**Comment by MaxJPRey** [comment]
Yes @PipKat , but all gathered under the same website.

**Comment by MaxJPRey** [comment]
Both the `FullDocumentation` and `Nightly Documentation` are now taking advantage of the `pyansys/actions`.
