### ISSUE TITLE
Migrate tools configuration to pyproject.toml

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/pyaedt#2073]
🐞 **Problem**
Even if this project is using a setup.py, it is possible to have a pyproject.toml file for declaring the configuration for the different tools used by the project. By doing so, it will be possible to remove some dotfiles at the base directory, like .coveragerc, .pylintrc, pytest.ini and any additional settings living inside the pre-commit-config.

**Comment by Samuelopez-ansys** [comment]
@MaxJPRey This issue could be closed right?

**Comment by MaxJPRey** [comment]
@Samuelopez-ansys Yes, we can now close this issue.
