### ISSUE TITLE
How do I make a variable parameter?

### ISSUE THREAD

**Issue by jpotter0** [pyansys/pyaedt#2075]
I think I figured it out in my simple model. I created 1 independent variable and one dependent variable. The geometry changes shape  like I want.

One peculiar issue, though. I have a non varying value y2=75. It is interpreted as mm. However, my variable z1 and dependent variable x1=2×z1 are both interpretation as met meters. This us confusing.

**Comment by maxcapodi78** [comment]
Hi @jpotter0 
look at the image below. I've created the variable y2 and x1 as per your input and using the evaluated_value field I can get the value in mm
numeric_value instead is providing the floating value (in mm)
![image](https://user-images.githubusercontent.com/77293250/205302292-2b6672d3-b910-4596-807b-421ea224afcb.png)
