### ISSUE TITLE
Cannot open a desktop instance in RHEL 7.9

### ISSUE THREAD

**Issue by huseyinuri** [pyansys/pyaedt#2082]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Recently moved from Windows to RHEL 7.9 and started to try pyaedt in my new os. Afaik, Red Hat maintains its Python distro and i really don't know wheather is it Cpython implementation or not. That's why i use Python3.7 that shipped with Ansys HFSS installation. However i get
 "AssertionError: Specified version 2022.1 is not known".
when i try to open new desktop session. My Linux machine already has licensed 2022.R1 up and running. Nothing wrong about it.

### Steps To Reproduce
```console
$ mkdir somedir && cd somedir
$ /opt/AnsysEM/v221/Linux64/commonfiles/CPython/3_7/linx64/Release/python/bin/python -m venv .venv
$ source .venv/bin/activate
$ git clone https://github.com/pyansys/pyaedt.git
$ cd pyaedt
$ python -m pip install .
$ python
>>> from pyaedt import Desktop
>>> d=Desktop("2022.1",non_graphical=False,new_desktop=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Desktop() got an unexpected keyword argument 'new_desktop'
>>> d=Desktop("2022.1",non_graphical=False,new_desktop_session=True)
pyaedt INFO: using existing logger.
/home/nuri/sil/pyaedt/pyaedt/misc/misc.py:15: UserWarning: No installed versions of AEDT are found in the system environment variables ``ANSYSEM_ROOTxxx``.
  "No installed versions of AEDT are found in the system environment variables ``ANSYSEM_ROOTxxx``."
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nuri/sil/pyaedt/pyaedt/generic/design_types.py", line 487, in Desktop
    aedt_process_id=aedt_process_id,
  File "/home/nuri/sil/pyaedt/pyaedt/desktop.py", line 401, in __init__
    self._main.student_version, version_key, version = self._set_version(specified_version, student_version)
  File "/home/nuri/sil/pyaedt/pyaedt/desktop.py", line 567, in _set_version
    assert specified_version in self.version_keys, "Specified version {} is not known".format(specified_version)
AssertionError: Specified version 2022.1 is not known
```
### Which Operating System are you using?

Linux

### Which Python version are you using?

3.7

### Installed packages

aiohttp==3.8.3
aiosignal==1.3.1
appdirs==1.4.4
async-timeout==4.0.2
asynctest==0.13.0
attrs==22.1.0
certifi==2021.10.8
cffi==1.15.0
chardet==3.0.4
charset-normalizer==2.1.1
clr-loader==0.2.4
cycler==0.10.0
distro==1.8.0
dotnetcore2==3.1.23
frozenlist==1.3.3
future==0.16.0
grpcio==1.26.0
idna==2.7
imageio==2.22.4
kiwisolver==1.3.2
matplotlib==3.1.1
multidict==6.0.3
numpy==1.21.2
packaging==21.3
pandas==1.3.5
Pillow==9.3.0
plumbum==1.8.0
pooch==1.6.0
protobuf==3.18.1
psutil==5.8.0
pyaedt==0.7.dev0
pycparser==2.21
pyparsing==2.4.7
python-dateutil==2.8.1
pythonnet==3.0.1
pytz==2019.3
pyvista==0.37.0
requests==2.20.1
rpyc==5.0.1
scipy==1.7.0
SCons==4.0.1
scooby==0.7.0
sip==4.19.17
six==1.11.0
typing-extensions==4.4.0
urllib3==1.24.3
vtk==9.2.2
wslink==1.9.1
yarl==1.8.2

**Comment by gmalinve** [comment]
Hi @huseyinuri,

was this suggestion helpful?
In case it was, please do let us know so we can close the issue.

Thanks!
