### ISSUE TITLE
Can't get get_solution_data to work 

### ISSUE THREAD

**Issue by jpotter0** [pyansys/pyaedt#2102]
Here's the code segment.:

    Fields = oDesign.GetModule("FieldsReporter")
    Fields.EnterQty("E")
    Fields.CalcOp("CmplxMag")
    Fields.CalcOp("ScalarZ")
    Fields.AddNamedExpression("Ezz", "Fields")
    variations = aedtapp.available_variations.nominal_w_values_dict
    variations["Ezz"] = ["1"]
    solutions = aedtapp.post.get_solution_data(expressions="Ezz",report_category="Fields",context="axis1",
                                       variations=variations,primary_sweep_variable="Distance")

Here's the error message:

pyaedt WARNING: Solution Data failed to load. Check solution, context or expression.
pyaedt WARNING: No Data Available. Check inputs

**Comment by jpotter0** [comment]
I got it working. I replaced the Fields definition by
Fields = Hfss().odesign.GetModule("FieldsReporter")

I was then able to extract my data with
Ezzz = solutions.primary_sweep_values.
Ezz is a list of data points of my on-axis field magnitude.

There appears to be a bug in HFSS. I've seen this before. The fields are initially normalized to 1 V, but the display says 1 J. It was not responsive to my attempt to actually set it to 1 J. I need to figure out what's going on because I need to find the integral of the data I lust extracted so I can normalize the fields to an average E0=1 MV/m.

One more layer has been peeled off the onion.

**Comment by Samuelopez-ansys** [comment]
Hi @jpotter0 ,

Could we close this issue?

**Comment by jpotter0** [comment]
Samuel,

Yes, I am able to access the data I need.

Thanks for all your help.

Best regards,

Jim


On December 13, 2022 11:43:54 AM MST, Samuel Lopez ***@***.***> wrote:
>Hi @jpotter0 ,
>
>Could we close this issue?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/pyansys/pyaedt/issues/2102#issuecomment-1349507109
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
James M. Potter, PhD, President
JP Accelerator Works, Inc. 
2245 47th Street
Los Alamos, NM 87644

TEL: (505) 690-8701

Sent from my Android device with K-9 Mail.
