### ISSUE TITLE
Bug located in Outline layer after stackup is modified

### ISSUE THREAD

**Issue by pyAnsysUser** [pyansys/pyaedt#2124]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

After the stackup is modified, the Outline layer is no longer present. Is this expected behavior?

The follow-up question will ask how to get the list of points for the outline layer, to be used in the outline argument for the edb.core_nets.plot() function.

### Steps To Reproduce

```
import os
from pyaedt import Edb,examples
edb_path = os.path.join(long_edb_path, 'edb\Galileo.aedb')
edb = Edb(edbpath=edb_path, edbversion="2022.2")
edb.save_edb_as(os.path.join(long_edb_path, 'Temp\edb\Galileo.aedb'))

add_layer='new_metal'
print(f'Before adding layer {add_layer} to {[lyr for lyr in edb.stackup.layers]}')
edb.stackup.add_layer(add_layer, method = 'add_on_top')
print(f'After adding layer {add_layer} to {[lyr for lyr in edb.stackup.layers]}')

edb.save_edb()
edb.close_edb()
```

Output:
pyaedt INFO: Logger is initialized in EDB.
pyaedt INFO: EDB Path C:\...\CODE_TEST\edb\Galileo.aedb
pyaedt INFO: EDB Version 2022.2
pyaedt INFO: EDB Standalone True
pyaedt INFO: Database Opened
pyaedt INFO: Cell Galileo_um Opened
pyaedt INFO: C:\...\Python\Python37\site-packages\pyaedt\dlls\EDBLib
pyaedt INFO: Refreshing the Components dictionary.
pyaedt INFO: Objects Initialized
pyaedt INFO: Builder was initialized.
pyaedt INFO: EDB was initialized.
Before adding layer new_metal to ['UNNAMED_000', 'TOP', 'UNNAMED_002', 'PWR', 'UNNAMED_004', 'LYR_1', 'UNNAMED_006', 'LYR_2', 'UNNAMED_008', 'GND', 'UNNAMED_010', 'BOTTOM', 'UNNAMED_012', 'Measures', 'SIwave Regions', 'Rats', 'Errors', 'Symbols', 'Postprocessing', 'Outline']
After adding layer new_metal to ['new_metal', 'UNNAMED_000', 'TOP', 'UNNAMED_002', 'PWR', 'UNNAMED_004', 'LYR_1', 'UNNAMED_006', 'LYR_2', 'UNNAMED_008', 'GND', 'UNNAMED_010', 'BOTTOM', 'UNNAMED_012', 'Measures', 'SIwave Regions', 'Rats', 'Errors', 'Symbols', 'Postprocessing']
pyaedt INFO: EDB file release time: 1.99ms

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

pyaedt v0.6.35
(package list not public)

**Comment by maxcapodi78** [comment]
@pyAnsysUser  I think this is a bug in EDB API. As far as I see you already opened the galileo in aedt (because you have alos the Siwave Regions layer) and then you are trying to edit it with Edb. There is a problem because of the named used in AEDT  vs the name expected in edb (Outline vs outline). I bet that if you start from galileo.brd, open in Edb and add a layer you will still have the outline layer.

**Comment by pyAnsysUser** [comment]
@maxcapodi78 this might be true, but this problem occurs in the tgz of my custom board, for which I am trying to solve this issue via the example project

**Comment by maxcapodi78** [comment]
@pyAnsysUser can you share on teams the project and code snippet?

**Comment by pyAnsysUser** [comment]
@maxcapodi78 the latest release has solved the issue with the outline deleting. Any ideas on how to get the list of points for edb.core_nets.plot()?
