### ISSUE TITLE
Could we have a new circuit port creating method by self-defined pin groups?

### ISSUE THREAD

**Issue by MaxJPRey** [pyansys/pyaedt#2132]
### Discussed in https://github.com/pyansys/pyaedt/discussions/2112

<div type='discussions-op-text'>

<sup>Originally posted by **raindigoa** December  7, 2022</sup>
Hello AE,

Here are two suggestions for edb function.

The first one is about a quite basic but unrealized method to have a new circuit port.
So far we could create the new circuit ports by the following methods while we use edb.siwave:
1. create_circuit_port_on_net
2. create_circuit_port_on_pin
3. create_circuit_port_on_components_no_pin_group

But none of the above methods allows user to create circuit port by a self-defined pin group.
It's not unusual case that we need to partition a whole bunch of pins into smaller groups to have a detailed study, so it would be nice to have such a function to do that.

The second request is about the port list in edb module, it seems there is no command that we can use to have an existed port list. If it is possible, I hope that we could have a command to list the existed ports and the corresponding positive/negative pins.

Would you please add these functions? Thank you.</div>

**Comment by pyAnsysUser** [comment]
If a pin that is within a pin group is specified as a terminal, is the pin treated as a pin group?
