### ISSUE TITLE
Enable multi-version documentation

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/pyaedt#2138]
💡 **Idea**
It would be awesome to implement the multi-version documentation feature for PyAEDT. Instead of forcing this project to adapt the whole CI/CD to the pyansys/actions pipeline, it is possible to just use the doc-deploy-dev and doc-deploy-stable to take advantage of multi-version. This simplifies the implementation process.

**Comment by MaxJPRey** [comment]
Yes, that would be the perfect approach here @jorgepiloto .
