### ISSUE TITLE
Enable extraction of field quantities during Maxwell (2D and 3D) transient simulation

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [pyansys/pyaedt#2151]
### Description of the feature

Enable extraction of field quantities during Maxwell (2D and 3D) transient simulation using the control program.  Here is the syntax in the native API to set up a python script for the control program
![image](https://user-images.githubusercontent.com/38879940/207826503-86a67305-9572-4802-9af2-026102ae2ee0.png)

### Steps for implementing the feature

1. Ensure that control program is part of the solution setup
2. Pass information to the method: 
 - field quantity
 - output file name
 - analysis setup.  
 - It is desirable (not sure it is possible) to return the data in the method rather than writing to a text file.  
3. Run transient simulation. Field data will be written to a file.

### Useful links and references

Some relevant methods:

- https://aedt.docs.pyansys.com/API/_autosummary/pyaedt.maxwell.Maxwell2d.setup_ctrlprog.html
- https://aedt.docs.pyansys.com/API/_autosummary/pyaedt.maxwell.Maxwell2d.src_dir.html

**Comment by Samuelopez-ansys** [comment]
@gmalinve Is this related to the new feature you added?

**Comment by gmalinve** [comment]
@Samuelopez-ansys @dcrawforAtAnsys yep! I implemented it in the previous release :)
well.. actually it was an old method and I improved it.

**Comment by Samuelopez-ansys** [comment]
Then this issue could be closed ? @gmalinve

**Comment by gmalinve** [comment]
@Samuelopez-ansys @dcrawforAtAnsys I'll close this one and as agreed with Devin I'll open an issue to implement a complete example for control program in pyaedt.
