### ISSUE TITLE
create_two_resistor_network_block bug

### ISSUE THREAD

**Issue by wilove997** [pyansys/pyaedt#2171]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

create_two_resistor_network_block function fails

### Steps To Reproduce

N/A

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.9

### Installed packages

N/A

**Comment by ansys-satyajeet** [comment]
@wilove997  What is the scenario where the function fails?
