### ISSUE TITLE
String is not formatted correctly in AEDT Message Manager

### ISSUE THREAD

**Issue by kbhagat-ansys** [pyansys/pyaedt#2194]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

When Running `pyaedt\examples\07-Circuit\Circuit_Example.py` I see the following AEDT Message Manager UI

![image](https://user-images.githubusercontent.com/83788850/209188794-c654bbcc-131f-497c-92a3-c019a3a39867.png)

### Steps To Reproduce

Run `pyaedt\examples\07-Circuit\Circuit_Example.py` with `close_on_exit=False`

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

N/A

**Comment by MaxJPRey** [comment]
Hi @kbhagat-ansys,
This has been fixed in release 0.6.38.

![image](https://user-images.githubusercontent.com/87315832/209306770-78a11147-2a4b-43f0-ac8a-1702d6b65a61.png)

Please let us know if you encounter any other issue.
Thanks.
