### ISSUE TITLE
Implement PEP517 with PyAEDT

### ISSUE THREAD

**Issue by MaxJPRey** [pyansys/pyaedt#2224]
### Description of the feature

`poetry` is based on [PEP517](https://peps.python.org/pep-0517).
To be able to use `pyaedt` as a dependency in a pyproject.toml, it must comply with PEP517.

**Comment by FranzForstmayr** [comment]
Duplicate of #1646

**Comment by MaxJPRey** [comment]
Duplicate of https://github.com/pyansys/pyaedt/issues/1646
