### ISSUE TITLE
Bug located in pyAEDT

### ISSUE THREAD

**Issue by KimMartinNielsen** [pyansys/pyaedt#2237]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Object name change in 3D component not recognized by pyAEDT. 

Dear Team, 
We are trying to open Icepak 3D component  - change the Name of all objects 3D component - and copy the object with new name to another Icepak Project,
However, the new names of the object does not seem to be saved, when calling ".modeler.get_objects_w_string" after name change - and it still refers to old names. 

Please find example and code attached in zip folder. 
And please let me know if you have any addiational questions. 

Best regards,
Kim
[BUGCompNames.zip](https://github.com/pyansys/pyaedt/files/10351186/BUGCompNames.zip)

### Steps To Reproduce

Unpack attached zip folder. 
Change path to .aedt example in ANSYSBug_test.py (line 7) 
Run Python code

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

aiohttp==3.8.1
aiosignal==1.2.0
altgraph==0.17.2
appdirs==1.4.4
async-timeout==4.0.2
attrs==22.1.0
cachetools==5.1.0
certifi==2022.5.18.1
cffi==1.15.1
charset-normalizer==2.0.12
clr-loader==0.2.3
configobj==5.0.6
cycler==0.11.0
et-xmlfile==1.1.0
fonttools==4.33.3
fpdf==1.7.2
frozenlist==1.3.1
future==0.18.2
google-api-core==2.8.0
google-api-python-client==2.48.0
google-auth==2.6.6
google-auth-httplib2==0.1.0
googleapis-common-protos==1.56.1
grpcio==1.46.1
httplib2==0.20.4
idna==3.3
imageio==2.22.0
jproperties==2.1.1
kaleido==0.2.1
kiwisolver==1.4.2
matplotlib==3.5.2
multidict==6.0.2
numpy==1.22.3
openpyxl==3.0.10
packaging==21.3
pandas==1.4.2
pefile==2022.5.30
Pillow==9.1.1
plotly==5.8.0
plumbum==1.7.2
protobuf==3.20.1
psutil==5.9.2
pyaedt==0.6.26
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pyinstaller==5.3
pyinstaller-hooks-contrib==2022.8
pyparsing==3.0.9
python-dateutil==2.8.2
pythonnet==3.0.1
pytz==2022.1
pyvista==0.36.1
pywin32==304
pywin32-ctypes==0.2.0
requests==2.27.1
rpyc==5.0.1
rsa==4.8
scooby==0.6.0
six==1.16.0
tenacity==8.0.1
tk==0.1.0
uritemplate==4.1.1
urllib3==1.26.9
vtk==9.2.0rc2
wslink==1.8.2
XlsxWriter==3.0.3
yarl==1.8.1

**Comment by gmalinve** [comment]
Hi  @KimMartinNielsen ,

As @wilove997 suggested you are not using any of the pyaedt functionalities to achieve the desired result but rather the native API. Pyaedt does that for you!
There's a specific method called: _copy_solid_bodies_from()_ which basically allows you to copy bodies from one design to another without to manually do it by yourself. It only requires as inputs the "origin" design and the list of bodies to copy. Please find below an example to achieve ehat you want:

`from pyaedt import Icepak

project_name = r"C:\Test\pyaedt_icepak_3d_comp\BUGCompNames\Project_test2.aedt"

ipkapp = Icepak(projectname=project_name, specified_version="2022.2")

user_defined_components = []
for comp_name in ipkapp.modeler.user_defined_components.keys():
    user_defined_components.append(ipkapp.modeler.user_defined_components[comp_name])

project_name = "IcepakCopiedProject"
design_name = "IcepakCopiedBodies"
new_design = Icepak(projectname=project_name, designname=design_name, specified_version="2022.2")

new_design.copy_solid_bodies_from(ipkapp, user_defined_components)

ipkapp.release_desktop(False, False)`

Hopefully it's clear enough!

Giulia

**Comment by gmalinve** [comment]
Hi @KimMartinNielsen ,

is it clear the provided example? can we close the issue or do you have any other doubt?

Thanks,

Giulia

**Comment by gmalinve** [comment]
Hi @KimMartinNielsen, 

I'm going to close this issue since we didn't get back any feedback.
For any doubt please feel free to open a new one and let us know.

Thanks,

Giulia
