### ISSUE TITLE
Nightly doc is not working anymore.

### ISSUE THREAD

**Issue by MaxJPRey** [pyansys/pyaedt#2250]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

See the [nightly-docs](https://github.com/pyansys/pyaedt/actions/workflows/nightly-docs.yml) history. 

The documentation from the main branch is built properly but is not deployed.

![image](https://user-images.githubusercontent.com/87315832/211294345-a2f3e1c6-cd9b-41ce-9ae4-1de34488eaa9.png)

### Steps To Reproduce

N/A.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

N/A.

**Comment by jorgepiloto** [comment]
Related with https://github.com/pyansys/actions/pull/131

**Comment by jorgepiloto** [comment]
Using [pyansys/actions@v3](actions.docs.pyansys.com/release/3.0/index.html) should fix this issue.

**Comment by MaxJPRey** [comment]
@jorgepiloto exactly. I have launched the build with one of my branch embedding the v3.
Thanks @jorgepiloto for the new release of pyansys/actions.
