### ISSUE TITLE
parameter  solution_type versus solutiontype

### ISSUE THREAD

**Issue by PipKat** [pyansys/PyAEDT#231]
In the FieldAnalysis3D class (pyaedt/application/Analysis3D),  solutiontype (with no hyphen) is used. In the FieldAnalysis2D class (Analysis2D in the same folder),  (and in most other places, solution_type is used.

**Comment by akaszynski** [comment]
@MaxJPRey, please submit a PR refactoring `solutiontype --> solution_type`.  Would be great to have more snakecase in our API.  See:
https://github.com/pyansys/PyAEDT/blob/efe8d219be974fa8a164d84ca9bc5c0e1b32256c/pyaedt/application/Analysis3D.py#L56-L59

**Comment by MaxJPRey** [comment]
@akaszynski I fixed that in an upcoming pull request. However, I can see that `projectname` and `designname` keyword argument are not snake_case. Should I create 2 new issues and fix them in 2 new separate PR?
