### ISSUE TITLE
Issue found in function create_gnd(PrimitivesCircuit.py) angle parameter not working for 180 and 270

### ISSUE THREAD

**Issue by amichel0205** [pyansys/pyaedt#2338]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Using the following function create_gnd(location=[gnd_position_x, position_y], angle=90).
It is working fine if angle = 0 or 90, if angle is set to 180 or 270 it is mot working and gnd is added as angle=0

### Steps To Reproduce

Using the following function create_gnd(location=[gnd_position_x, position_y], angle=180).
angle 180 and 270 are not working

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.8

### Installed packages

C:\Users\amichel>python -m pip freeze
aiohttp==3.8.1
aiosignal==1.2.0
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
async-timeout==4.0.2
attrs==21.2.0
backcall==0.2.0
bleach==4.1.0
cffi==1.15.0
charset-normalizer==2.0.9
colorama==0.4.4
cycler==0.11.0
debugpy==1.5.1
decorator==5.1.0
defusedxml==0.7.1
entrypoints==0.3
fonttools==4.28.5
frozenlist==1.2.0
idna==3.3
imageio==2.13.4
importlib-resources==5.4.0
ipykernel==6.6.0
ipython==7.30.1
ipython-genutils==0.2.0
ipywidgets==7.6.5
jedi==0.18.1
Jinja2==3.0.3
jsonschema==4.3.2
jupyter==1.0.0
jupyter-client==7.1.0
jupyter-console==6.4.0
jupyter-core==4.9.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.2
kiwisolver==1.3.2
MarkupSafe==2.0.1
matplotlib==3.5.1
matplotlib-inline==0.1.3
meshio==4.4.6
mistune==0.8.4
multidict==5.2.0
nbclient==0.5.9
nbconvert==6.3.0
nbformat==5.1.3
nest-asyncio==1.5.4
notebook==6.4.6
numpy==1.21.5
packaging==21.3
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
Pillow==8.4.0
plumbum==1.7.1
prometheus-client==0.12.0
prompt-toolkit==3.0.24
pyaedt==0.4.18
pycparser==2.21
Pygments==2.10.0
pyparsing==3.0.6
pypiwin32==223
pyrsistent==0.18.0
python-dateutil==2.8.2
pythonnet==2.5.2
pyvista==0.32.1
pywin32==303
pywinpty==1.1.6
pyzmq==22.3.0
qtconsole==5.2.2
QtPy==2.0.0
rpyc==5.0.1
scooby==0.5.10
Send2Trash==1.8.0
six==1.16.0
terminado==0.12.1
testpath==0.5.0
tornado==6.1
traitlets==5.1.1
typing_extensions==4.0.1
vtk==9.1.0
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.2
wslink==1.3.0
yarl==1.7.2
zipp==3.6.0

**Comment by gmalinve** [comment]
@amichel0205 we can close this issue based on our conversation this morning, what do you think?

**Comment by amichel0205** [comment]
After checking with Giulia:

Angle 0, 90 and 180 are working as expected.
Only 270 is not working but it is an issue of AEDT API
