### ISSUE TITLE
Bug located in SolveSetup.py

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [pyansys/pyaedt#2357]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

If the logger isn't defined, calling ``create_linear_count_sweep()`` from the setup throws an error when trying to write to self.logger.

### Steps To Reproduce

Turn logging off and then call ``create_linear_count_sweep()``  from the application instance  (i.e. Hfss)

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

# #############################################################################
# requirements
# #############################################################################
cff1==1.15.0; python_version > '3.6' and sys_platform == 'linux'
# https://github.com/tomerfiliba-org/rpyc
# License: MIT

dotnetcore2==3.1.23; python_version > '3.6' and sys_platform == 'linux'
# https://github.com/dotnet/core
# License: MIT

pythonnet==3.0.1; python_version > '3.6'
# https://github.com/pythonnet/pythonnet
# License: MIT

pywin32>=301; python_version > '3.6' and sys_platform == 'windows'
# https://github.com/mhammond/pywin32
# License: PSF

rpyc==5.3.0; python_version > '3.6'
# https://github.com/tomerfiliba-org/rpyc
# License: MIT

# #############################################################################
# optional
# #############################################################################

matplotlib==3.6.3; python_version > '3.6'
# License: https://github.com/matplotlib/matplotlib/blob/master/LICENSE/LICENSE
# License: PSF

numpy==1.24.1; python_version > '3.7'
# License: BSD-3-Clause License

pandas==1.5.2; python_version > '3.7'
pandas==1.3.5; python_version == '3.7'
# License: BSD-3-Clause License

psutil==5.9.4; python_version > '3.6'
# License: BSD-3-Clause License

pyvista==0.37.0; python_version > '3.6'
# License: MIT

**Comment by Samuelopez-ansys** [comment]
Hi @dcrawforAtAnsys ,

I can not reproduce the issue. How are you disabling the logger? 

I have tried the following code:

```
import pyaedt

pyaedt.settings.use_grpc_api = False

app = pyaedt.Hfss(specified_version="2023.1", non_graphical=False, new_desktop_session=False)

pyaedt.settings.logger.disabled = True

setup = app.create_setup("MySetup")
setup.props["Frequency"] = "1GHz"
setup.props["BasisOrder"] = 2
setup.props["MaximumPasses"] = 1
setup.update()
app.create_linear_count_sweep("MySetup", "GHz", 0.8, 1.2, 401)

app.release_desktop(False, False)
```
