### ISSUE TITLE
Bug located in constants.unit_converter

### ISSUE THREAD

**Issue by jsalant22** [pyansys/pyaedt#2387]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The constants.unit_converter() method does not work for Power. AEDT_UNITS has options to go between Watts and dBm/dBW, but unit_converter just scales based on a constant factor that is specified for each.

`value = value * AEDT_UNITS[unit_system][input_units] / AEDT_UNITS[unit_system][output_units]`

The above works if going from Watts to milliwatts or kilowatts or similarly from dBm to dBW, but will not work to change from Watts to dBm (or vice versa).

### Steps To Reproduce

1. Specify a power in Watts
2. Use constants.unit_converter() to convert to dBm or dBW.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

altgraph==0.17.3
anyio==3.6.2
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
attrs==22.2.0
Babel==2.11.0
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.1
certifi==2022.12.7
cffi==1.15.1
cfgv==3.3.1
charset-normalizer==2.1.1
click==8.1.3
click-plugins==1.1.1
cligj==0.7.2
clr-loader==0.2.5
colorama==0.4.6
cycler==0.11.0
debugpy==1.6.4
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.6
entrypoints==0.4
exceptiongroup==1.1.0
fastjsonschema==2.16.2
filelock==3.9.0
Fiona==1.8.22
fonttools==4.38.0
future==0.18.3
geopandas==0.10.2
identify==2.5.13
idna==3.4
imageio==2.24.0
importlib-metadata==6.0.0
importlib-resources==5.10.2
iniconfig==2.0.0
ipykernel==6.16.2
ipython==7.34.0
ipython-genutils==0.2.0
ipywidgets==8.0.4
jedi==0.18.2
Jinja2==3.1.2
json5==0.9.11
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.4.4
jupyter-server==1.23.4
jupyter_client==7.4.8
jupyter_core==4.12.0
jupyterlab==3.5.2
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.5
jupyterlab_server==2.18.0
kiwisolver==1.4.4
MarkupSafe==2.1.1
matplotlib==3.5.3
matplotlib-inline==0.1.6
mistune==2.0.4
munch==2.5.0
nbclassic==0.4.8
nbclient==0.7.2
nbconvert==7.2.7
nbformat==5.7.1
nest-asyncio==1.5.6
networkx==2.6.3
nodeenv==1.7.0
notebook==6.5.2
notebook_shim==0.2.2
npm==0.1.1
numpy==1.21.6
optional-django==0.1.0
osmnx==1.1.2
packaging==22.0
pandas==1.3.5
pandocfilters==1.5.0
parso==0.8.3
pefile==2022.5.30
pickleshare==0.7.5
Pillow==9.4.0
pkgutil_resolve_name==1.3.10
platformdirs==2.6.2
plotly==5.11.0
pluggy==1.0.0
plumbum==1.8.1
pooch==1.6.0
pre-commit==2.21.0
prometheus-client==0.15.0
prompt-toolkit==3.0.36
psutil==5.9.4
pyaedt==0.6.43
pycparser==2.21
pygeos==0.14
Pygments==2.14.0
pyinstaller==5.7.0
pyinstaller-hooks-contrib==2022.15
pyparsing==3.0.9
pyproj==3.2.1
pyrsistent==0.19.3
pytest==7.2.1
python-dateutil==2.8.2
pythonnet==3.0.1
pytz==2022.7
pyvista==0.37.0
pywin32==305
pywin32-ctypes==0.2.0
pywinpty==2.0.10
PyYAML==6.0
pyzmq==24.0.1
qtconsole==5.4.0
QtPy==2.3.0
requests==2.28.1
rpyc==5.3.0
Rtree==1.0.1
scooby==0.7.0
Send2Trash==1.8.0
Shapely==1.8.5.post1
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.2.post1
tenacity==8.1.0
terminado==0.17.1
tinycss2==1.2.1
tk==0.1.0
tomli==2.0.1
tornado==6.2
tqdm==4.64.1
traitlets==5.8.0
typing_extensions==4.4.0
urllib3==1.26.13
utm==0.7.0
virtualenv==20.17.1
vtk==9.2.5
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.4.2
widgetsnbextension==4.0.5
zipp==3.11.0

**Comment by maxcapodi78** [comment]
@jsalant22 that was missed. I'm adding it but to use it cannot be like you showed since conversion dB requires a method and not a linear multiplier constant.

you can use unit_converter method in constants file.

```
uc = constants.unit_converter
uc(1,"Power", "W", "dBW")
Out[5]: 0.0
uc(3,"Power", "W", "dBW")
<class 'function'>
Out[6]: 4.771212547196624
uc(3,"Power", "W", "dBm")
<class 'function'>
Out[7]: 34.771212547196626
uc(34.7,"Power", "dBm", "W")
<class 'float'>
Out[8]: 2.951209226666387
uc(34.77,"Power", "dBm", "W")
<class 'float'>
Out[9]: 2.999162518987653
uc(34.77,"Power", "dBm", "dBW")
<class 'function'>
Out[10]: 4.770000000000003
```

or eventually 

```
AEDT_UNITS[unit_system][output_units](value,False)
```
