### ISSUE TITLE
edb sources set attribute

### ISSUE THREAD

**Issue by boyang2022** [pyansys/pyaedt#2488]
### Description of the feature

set the attribute of edb.sources. For example the amplitude of a voltage source.
![image](https://user-images.githubusercontent.com/93125854/219322710-8ac0cb56-047d-4edf-9b1b-52f342f3b7bb.png)

**Comment by svandenb-dev** [comment]
Hi @boyang2022,
I will add in the feature to implement. Thanks for your feedback

**Comment by svandenb-dev** [comment]
fixed
