### ISSUE TITLE
Bug located in ...module 'pyaedt' has no attribute 'downloads'

### ISSUE THREAD

**Issue by kunal-3196** [pyansys/pyaedt#2528]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

module 'pyaedt' has no attribute 'downloads'

### Steps To Reproduce

after importing '*' from pyaedt, same issue is occuring

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.9

### Installed packages

module 'pyaedt' has no attribute 'downloads'

not sure if bug or not

**Comment by gmalinve** [comment]
Hi @kunal-3196 ,

Have you tried to import as: from pyaedt.downloads import * if you want to import all methods or otherwise import only the method you are interested, for example: from pyaedt.downloads import download_file ?

Kind regards,

Giulia

**Comment by kunal-3196** [comment]
![image](https://user-images.githubusercontent.com/68815884/222878979-acd9d24d-7231-4d3c-b8aa-1860155b2056.png)
its not having downloads

**Comment by gmalinve** [comment]
Hi @kunal-3196 ,

Which version are you using? could you please download the latest release and see if the issue persist?

Thanks,

Giulia
