### ISSUE TITLE
Bug Python exits with many error messages when trying to use Hfss()

### ISSUE THREAD

**Issue by jpotter0** [pyansys/pyaedt#2531]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

My Python program using pyaedt was working three weeks ago. Now it crashes with multiple error messages on a call to Hfss, with or without arguments, either aedtapp = Hfss(projectname=project_name, designname=design_name, solution_type="Eigenmode",specified_version=version) or aedtapp = Hfss() causes program to crash.

### Steps To Reproduce

"""Script for IHDTL HFSS design using PyAEDT."""

# %% Imports
import math
import os
from typing import TextIO

import pyaedt
from pyaedt import Desktop
from pyaedt import Hfss

# %% Code

directory = "C:\Jims Files\\Nusano\IHDTL"
tanknumb = "7"
tank_name = 'C:\Jims Files\\Nusano\IHDTL\IHDTL_Tank'+tanknumb+'.aedt'
project_name = tank_name

design_name = "ihdtl"
version = "2022.2"
aedtapp = Hfss(projectname=project_name, designname=design_name, solution_type="Eigenmode",specified_version=version)
#aedtapp = Hfss()

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.8

### Installed packages

![RESULT~1](https://user-images.githubusercontent.com/45086768/221377392-8a38a34e-e879-4b6a-8df4-d7b74d99b174.JPG)

**Comment by Samuelopez-ansys** [comment]
@jpotter0 Please install a new virtual environment with only PyAEDT and test it. If does work, install Pyside2 and test it again. Let us know what happens.

**Comment by jpotter0** [comment]
OK, Samuel. I will do that.

On February 27, 2023 7:11:39 AM MST, Samuel Lopez ***@***.***> wrote:
>@jpotter0 Please install a new virtual environment with only PyAEDT and test it. If does work, install Pyside2 and test it again. Let us know what happens.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/pyansys/pyaedt/issues/2531#issuecomment-1446391012
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
James M. Potter, PhD, President
JP Accelerator Works, Inc. 
2245 47th Street
Los Alamos, NM 87644

TEL: (505) 690-8701

Sent from my Android device with K-9 Mail.

**Comment by jpotter0** [comment]
Creatin a  new environment fixed the problem. I was unable to reproduce the problem in the new environment.
