### ISSUE TITLE
Contribute link missing

### ISSUE THREAD

**Issue by akaszynski** [pyansys/pyaedt#2549]
There seems to be no way to get to the contribute link: https://aedt.docs.pyansys.com/release/0.6/Contributing.html from https://aedt.docs.pyansys.com/release/0.6/

**Comment by PipKat** [comment]
The More option that I see in the doc for the dev guide isn't showing:
![image](https://user-images.githubusercontent.com/84872299/221970025-64627e92-537e-4686-bf43-bb42d6734adf.png)

**Comment by maxcapodi78** [comment]
I've fixed broken link. I'm closing this issue
