### ISSUE TITLE
Potential incompatibility with the rest of PyAnsys libraries

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/pyaedt#2551]
On the https://github.com/pyansys/pyansys-dev repository (in which we check that all "dev" versions for the public PyAnsys projects are compatible) we have identified some issues with PyAEDT's compatibility with the rest of the libraries. It seems like you are pinning down a specific NumPy version, 1.24.2 for Python 3.7 as well. Though support for Python 3.7 is expected to be dropped, it would be best to solve it.

https://github.com/pyansys/pyansys-dev/actions/runs/4299440263/jobs/7494650056

It seems that PyAEDT is forcing 1.24.2 for Python3.7, which is not possible since that numpy version is not supported by Python 3.7. You should adapt your setup.py file to allow lower numpy versions for Pytthon 3.7. Probably ``numpy==1.21.6``.

Pinging @MaxJPRey

**Comment by maxcapodi78** [comment]
@RobPasMue thanks for pointing this.

**Comment by RobPasMue** [comment]
Problem was with the way that the system version was being parsed. This has been solved by @maxcapodi78 in #2546 =)

Thanks @maxcapodi78!
