### ISSUE TITLE
Revaluate Scratch approach for pytest/unittest

### ISSUE THREAD

**Issue by voss70** [pyansys/pyaedt#257]
Define a standard approach for defining scratch paths for unit testing (pytest and unittest) that will work across CPython and IronPython on windows and linkx

**Comment by akaszynski** [comment]
Is it possible to use https://docs.pytest.org/en/6.2.x/tmpdir.html within unittest as well on IronPython?

**Comment by Alberto-DM** [comment]
The unit test setup and teardown have been completely refactored. 
The module ``tempfile`` is used and the scratch temp folder is created under ``tempfile.gettempdir()``
