### ISSUE TITLE
Return a valid plotter object from plotting functions

### ISSUE THREAD

**Issue by rajesh1359** [pyansys/pyaedt#2598]
### Description of the feature

Most of the plotting function are returning pyvista plotter object back after showing the pyvista window. 

For example, polar_plot_3d_pyvista returns plotter after plotter.show() function. Once we close ( by using show function) a plotter, it is mostly of no use (if I am not missing anything).

What would be uses of the plotter object that we return. Would it be possible to create a copy of pyvista plotter and return so that it can be used later? I tried using copy module it didn't work.

### Steps for implementing the feature

Create a copy of plotter before using show function and return it

**Comment by Samuelopez-ansys** [comment]
Hi @rajesh1359 ,

This is a PyVista limitation, once it is shown, you can not reuse the object. We can not copy either the object:
https://github.com/pyvista/pyvista/issues/3073

Please submit an issue in PyVista if you need it.

We will refactor polar_plot_3d_pyvista method to return the object when "show" is disabled
