### ISSUE TITLE
hfss3dlayout export_profile 

### ISSUE THREAD

**Issue by ring630** [pyansys/pyaedt#2603]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The existing code pass wrong variation_string format.

https://github.com/pyansys/pyaedt/blob/9fd4ab01c747ded675599990dc451ef35d8b01df/pyaedt/application/Design.py#L1137

It passes 
'viatotrace=5mm,viatovia=10mm,w1=1mm,sp=0.5mm,len=50mm'
However, it should be like below
"len=\'50mm\' pyaedt_evaluator=\'0mm\' sp=\'0.5mm\' viatotrace=\'5mm\' viatovia=\'10mm\' w1=\'1mm\'"

In addition, it is missing **pyaedt_evaluator** which is a hidden variable.

### Steps To Reproduce

h3d.export_profile()

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

all

**Comment by Samuelopez-ansys** [comment]
Close #2608
