### ISSUE TITLE
Add options to setup creation ...

### ISSUE THREAD

**Issue by cristianbabetto** [pyansys/pyaedt#2615]
### Description of the feature

Add option "Evaluate cache after pass" and "Evaluate cache vs freq" in setup creation.

In eddy-current solver, add "save field option for all frequencies"  and for single frequencies only (flags in the GUI).

**Comment by gmalinve** [comment]
Hi @cristianbabetto,

I just created a PR to add this feature. 
It should be in the next release.
Methods that have changed are add_eddy_current_sweep (new input save_all_fields) and enable_expression_cache (two new inputs to enable the cache expressions).

Thanks,

Giulia
