### ISSUE TITLE
Add __getitem__() to Edb class

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [pyansys/pyaedt#2645]
### Description of the feature

Make Edb class consistent with other applications by allowing parameter definition and assignment via the ``__getitem__()`` and ``__setitem()__`` methods.  For example:
```python
edb = Edb()
edb["s1"]= "0.3 mm"
```

### Steps for implementing the feature

Create a new ``__setitem__()`` and ``__getitem__()`` method and call ``add_design_variable()`` from the ``__setitem__()`` method.

### Useful links and references

https://www.geeksforgeeks.org/__getitem__-and-__setitem__-in-python/
https://stackoverflow.com/questions/43627405/understanding-getitem-method

**Comment by maxcapodi78** [comment]
@dcrawforAtAnsys , @ring630 , @svandenb-dev I've created PR #2652 
Feel free to comment here or in the PR if you like the approach
