### ISSUE TITLE
Stackup.get_layout_thickness() should be a property

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [pyansys/pyaedt#2647]
### Description of the feature

Methods that only return a value should be properties. In this case without a setter.

```python
@property
def layout_thickness(self):
   return self.get_layout_thickness()
```
The ``get_layout_thickness()`` method should then be moved to a hidden method and later deprecated. 

### Steps for implementing the feature

Use the `@property` decorator.

### Useful links and references

https://www.freecodecamp.org/news/python-property-decorator/

**Comment by svandenb-dev** [comment]
@dcrawforAtAnsys done
