### ISSUE TITLE
Instantiate Hfss instance from Edb

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [pyansys/pyaedt#2665]
### Description of the current limitations

A common workflow will involve the following setps:

1. creation or preparation of an Edb instances
2. open this Edb instance in electronics desktop
3. further setup, solve, post-processing, etc.
The current syntax to do this is repeated in many examples and should be built into the ``pyaedt.Hfss3dLayout`` class.

### Code sample expected

```python
edb = Edb()
# Do some stuff to the edb object
hfss_app = edb.hfss()
```

**Comment by dcrawforAtAnsys** [comment]
This will be very difficult as the Edb instance needs to be closed inside the class method.

**Comment by svandenb-dev** [comment]
@dcrawforAtAnsys as a side note you can open edb for read only from HFSS 3D layout if needed. 
hfss = Hfss3DLayout(path_to_edb / aedt file)
edb = hfss.modeler.edb
this will open edb as non standalone so that you can query edb data with hfss open.
