### ISSUE TITLE
Remove empty layer in EDB and/or HFSS3DLayout

### ISSUE THREAD

**Issue by Samuelopez-ansys** [pyansys/pyaedt#2720]
### Description of the feature

Implement a method to remove a layer with no geometries in EDB and HFSS3DLayout

**Comment by Samuelopez-ansys** [comment]
@svandenb-dev @isaacansys Do you the EDP API command to delete a Layer? I think it could be useful a method to clean all layers without geometries.

**Comment by isaacansys** [comment]
@Samuelopez-ansys @svandenb-dev I think you would have to create a new LayerCollection with the layer removed.  We have to be very careful that nothing is in that layer (no shapes, no padstack instances starting/stopping there, etc.), however, or else objects will end up appearing elsewhere if we don't also delete/adjust them.

**Comment by svandenb-dev** [comment]
@Samuelopez-ansys yes I can have a look like Isaac Said there are some points to check and maybe adjusting some definition before deleting.  Assigning this bug to myself to keep track.

**Comment by svandenb-dev** [comment]
@Samuelopez-ansys there is a command in Pyaedt:
edb.stackup.remove_layer(layer_name)
Is it not working as expected ?
