### ISSUE TITLE
Improve Edb syntax and readability

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [pyansys/pyaedt#2754]
### Description of the current limitations

1. Deprecate ``pyaedt.edb.change_design_variable_value()``
2. Deprecate ``pyaedt.edb.add_design_variable()``
3. Deprecate ``pyaedt.ede.add_project_variable()``
4. Deprecate ``pyaedt.edb.get_variable()``
5. Deprecate ``pyaedt.edb.design_variables()``
6. Deprecate ``pyaedt.edb.project_variables()``
7. Replace ``pyaedt.edb.variables`` with ``var_names, variables = edb.items()``

- TMost are all handled by the ``__setitem__()`` and ``__getitem__()`` and this will simplify readability and documentation.

### Code sample expected

See the Edb getter and setters.

**Comment by maxcapodi78** [comment]
@dcrawforAtAnsys  I don't agree much on that. While I'm in favour aof getters and setters we need always to have the simple method calls especially for python beginners. So we can improve the __getitem__ and setitem
