### ISSUE TITLE
Improve "find_and_fix_disjoint_nets"

### ISSUE THREAD

**Issue by amichel0205** [pyansys/pyaedt#2788]
### Description of the feature

On large board, more specifically for PI application when doing a cutout for a specific power rail, the cutout will create a lot of disjoints nets on GND nets(or whatever nets which becomes disjoint).
Running find_and_fix_disjoint_nets on the generate cutout will create tens of different nets from GND and rename.
The issue is that the net keeping name GND(or whatever nets which becomes disjoint) is defined randomly which leads of having a very small piece of original GND net keeping the name GND when the largest piece being rename.
A possible consequence is to have port reference lost.

To overcome this issue, from all new nets created, we should identify the net with largest area and keep for it the original name (GND or whatever nets which becomes disjoint)

**Comment by MaxJPRey** [comment]
Fixed by #2791.
