### ISSUE TITLE
How do I get the imaginary component of frequency? I need to calculate the Q.

### ISSUE THREAD

**Issue by jpotter0** [pyansys/pyaedt#2804]
Here is the code snippet:

    setup = "Setup"+str(cellnum)
    running = aedtapp.analyze_setup(setup)
    post = aedtapp.post
    data = post.get_solution_data("re(Mode(1))")
    f_Hz = data.data_real()
    df_Hz = data.data_imag()
    fff = float(f_Hz[0])

I have the lossy surfaces defined using the Python script from HFSS. The method of using objects made from surfaces doesn't work for me because the curvilinear coordinates are turned off HFSS for these objects, which affects frequency accuracy.

I need to calculate the Q, or get the Q directly.

Jim

**Comment by Samuelopez-ansys** [comment]
Hi @jpotter0 ,

The problem of getting 're(Mode(1))' is you are retrieving the real part of Mode(1), so you are not getting the imag. part. 

Try:

data_im = post.get_solution_data("im(Mode(1))")
data_im .data_real()

OR another option could be:

data = post.get_solution_data("Mode(1)")

But I am not sure if this last option works or not, please let me know.

**Comment by jpotter0** [comment]
Thanks, Samuel! I'll check it out and get back to you.- Jim

On April 11, 2023 10:08:57 AM MDT, Samuel Lopez ***@***.***> wrote:
>Hi @jpotter0 ,
>
>The problem of getting 're(Mode(1))' is you are retrieving the real part of Mode(1), so you are not getting the imag. part. 
>
>Try:
>
>data_im = post.get_solution_data("im(Mode(1))")
>data_im .data_real()
>
>OR another option could be:
>
>data = post.get_solution_data("Mode(1)")
>
>But I am not sure if this last option works or not, please let me know.
>
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/pyansys/pyaedt/issues/2804#issuecomment-1503688301
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
James M. Potter, PhD, President
JP Accelerator Works, Inc. 
2245 47th Street
Los Alamos, NM 87644

TEL: (505) 690-8701

Sent from my Android device with K-9 Mail.

**Comment by jpotter0** [comment]
Samuel,

The attached screen shot shows what works. I 
don't know why there's no data on the f_Hz line, 
but it works in the calculation when I get the frequency in MHz.

Best regards,

Jim


At 10:08 AM 4/11/2023, you wrote:

**Comment by jpotter0** [comment]
It looks like the screenshot didn't show up in the email answer. Here it is:

![Data screen shot from IHDTL_CALC 2023040901](https://user-images.githubusercontent.com/45086768/231328526-7065ad62-c081-4aad-b3c5-1d6e4b3764d0.jpg)

**Comment by Samuelopez-ansys** [comment]
Hi @jpotter0 any update?

**Comment by jpotter0** [comment]
a modification of your suggestion cleared up the problem.
