### ISSUE TITLE
Missing feature to 3DL Padstack Definition 

### ISSUE THREAD

**Issue by housamomar** [pyansys/pyaedt#2856]
### Description of the feature

In current edb.core_padstack.create_padstack, its is not possible to set diffrent paddiam per layer

### Steps for implementing the feature

Hi @ring630, kindly will be possibe to implement this feature

**Comment by ring630** [comment]
@housamomar the functionality is here already

padstack.pad_by_layer[pad.via_stop_layer].parameters = "1mm"

I made some changes to this method. Once it is merged, you pass a dictionary

padstack.pad_by_layer[pad.via_stop_layer].parameters = {"Diameter": "1mm"}
