### ISSUE TITLE
Bug in create_padstack method

### ISSUE THREAD

**Issue by housamomar** [pyansys/pyaedt#2857]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The startlayer & endlayer input arguments of **create_padstack** method do not work

### Steps To Reproduce

Hi @ring630

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

pyaedt 0.6.71

**Comment by ring630** [comment]
@housamomar start_layer and end_layer input args are removed
