### ISSUE TITLE
Bug located in aedtapp.modeler.primitives[obj_name].faces

### ISSUE THREAD

**Issue by jpotter0** [pyansys/pyaedt#2895]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

I have an HFSS model. I can identify the 3 faces to which I wish to apply H boundary conditions. I do this by using the largest_faces method. I then get a list of all the faces. Then I remove the 3 H boundary faces from the list. Then I use that list to create conducting boundaries by using an HFSS script because the create objects from faces method messes up my frequency calculations due to a "feature" oh HFSS with respect to mesh generation. I will attach screen shots that show the 5 largest faces, the face IDs of the 3 I have selected, a list of all the faces, and the code by which I remove the selected along with the list of the remaining faces.

There are two problems. Face 255 appears in the list of largest faces and is one of my H boundary faces. However, face 255 does not appear in the list of all faces. Iturns out that face 220 is also missing from the list. There are 18 faces in the list, but HFSS shows that there are 20 faces total.

The second problem is that face 29 is not removed. Maybe there is an issue with how I am removing the faces from the list in python. Two o the faces I want to remove are not there to start with and one face I want to remove is not removed. If that's a Python problem, it doesn't relate to the fact that the list of faces is incomplete..

I don't know how to create a simple case to demonstrate this problem.

Here are the screen shots. 

![List of 5 largest faces](https://user-images.githubusercontent.com/45086768/233632597-cb4b07dc-12cc-49a5-b741-a6603e384313.jpg)

![IDs of selected faces](https://user-images.githubusercontent.com/45086768/233632485-2f74ba08-0814-4eb9-8553-19606bb4fd36.jpg)

![List of all faces](https://user-images.githubusercontent.com/45086768/233632555-a83b9642-c71e-4c59-a46c-2c44e640fa5f.jpg)

![List of remaining faces](https://user-images.githubusercontent.com/45086768/233632644-35d9fe7d-a761-4b09-94bc-996296fbf1ad.jpg)

![List of faces from HFSS](https://user-images.githubusercontent.com/45086768/233632806-b110b0ba-aaae-4b6c-a8be-21415982d1a3.jpg)

![Screen shot of conducting boundaries](https://user-images.githubusercontent.com/45086768/233632836-3d95930a-0b52-4f7c-8ba1-f7e472c625c7.jpg)

### Steps To Reproduce

1. Get the 5 largest faces
2. Select the 3 faces from that list that correspond to myH boundary faces.
3. Create H boundaries for those faces. All three boundaries are created correctly.
4. Get the list of all faces. 
5. Remove the 3 selected faces.
6. Create conducting boundaries on thee remaining faces.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.8

### Installed packages

![list of installed packages](https://user-images.githubusercontent.com/45086768/233637714-bca96123-6814-4e13-9345-3875eccdfd42.jpg)

**Comment by fwlfHS** [comment]
At least to your 2nd problem: Face 29 is not removed, because `face_id2` contains the id object whereas  `face.id` returns an integer. The comparison will always fail. So the location where you define `face_id2` should be adjusted.

**Comment by jpotter0** [comment]
For whatever reason fixing the   face_id2 = faces_largest[3].id statement to get the face id number insteadd f thye face id object fixed both issues. Thanks!
