### ISSUE TITLE
Add method to rename nets in EDB

### ISSUE THREAD

**Issue by pyAnsysUser** [pyansys/pyaedt#2922]
### Description of the feature

the EDB nets have a name property, suggest allowing user to change net name

**Comment by maxcapodi78** [comment]
@pyAnsysUser you can do it already
```
edb = Edb()
edb.nets["GND"].name = "GND2"

```

**Comment by pyAnsysUser** [comment]
Hello,
I found I was trying to change the capitalization on a net that already existed. This, I believe, is not supported even in the GUI version of SIwave. Changing to an intermediate name then renaming for capitalization worked.
