### ISSUE TITLE
Student Version of AEDT not working with PyAEDT

### ISSUE THREAD

**Issue by RaisinO** [pyansys/pyaedt#2942]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

I started this in the Q&A section but thought maybe I should post here instead.

I've been struggling to fix an error that has come up after building a Spyder PyAEDT environment in Anaconda and am hoping that someone can point me in the right direction to get things up and running.

I am using the student version of AEDT on a Windows 10 workstation and noticed that when the version of AEDT is called out in some examples, it wasn't clear how to populate the field for the student version as the field usually says '2023.1' while the student version has a different path/version that does not match this format. This is just a guess on my part as to what may be the root of the issue since the error seems to be related to file pathing.

### Steps To Reproduce

Running the following, as suggested in another thread, before running an example:
```
import pyaedt
pyaedt.version
'0.6.73'
```
Followed by:
```
import pyaedt

app = pyaedt.Hfss()
app.release_desktop()
```
Yields the error that I was receiving when I would try to run an example, which is as follows:
```
pyaedt INFO: using existing logger.
pyaedt INFO: AEDT installation Path C:\Program Files\AnsysEM\Ansys Student\v222\Win64
pyaedt INFO: Launching AEDT with the gRPC plugin.
pyaedt INFO: New AEDT session is starting on gRPC port 51737
Exception in thread Thread-6 (launch_desktop_on_port):
Traceback (most recent call last):
  File "C:\anaconda3\envs\spyder-pyaedt-env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\anaconda3\envs\spyder-pyaedt-env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\anaconda3\envs\spyder-pyaedt-env\lib\site-packages\pyaedt\desktop.py", line 79, in launch_desktop_on_port
    subprocess.Popen(" ".join(command), env=my_env, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
  File "C:\anaconda3\envs\spyder-pyaedt-env\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 109, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)
  File "C:\anaconda3\envs\spyder-pyaedt-env\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\anaconda3\envs\spyder-pyaedt-env\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Exception in thread Thread-7 (launch_desktop_on_port):
Traceback (most recent call last):
  File "C:\anaconda3\envs\spyder-pyaedt-env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\anaconda3\envs\spyder-pyaedt-env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\anaconda3\envs\spyder-pyaedt-env\lib\site-packages\pyaedt\desktop.py", line 79, in launch_desktop_on_port
    subprocess.Popen(" ".join(command), env=my_env, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
  File "C:\anaconda3\envs\spyder-pyaedt-env\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 109, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)
  File "C:\anaconda3\envs\spyder-pyaedt-env\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\anaconda3\envs\spyder-pyaedt-env\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
pyaedt ERROR: Failed to start AEDT on port 52128.
Traceback (most recent call last):

  Cell In[1], line 3
    app = pyaedt.Hfss()

  File C:\anaconda3\envs\spyder-pyaedt-env\lib\site-packages\pyaedt\generic\design_types.py:66 in Hfss
    return app(

  File C:\anaconda3\envs\spyder-pyaedt-env\lib\site-packages\pyaedt\hfss.py:166 in __init__
    FieldAnalysis3D.__init__(

  File C:\anaconda3\envs\spyder-pyaedt-env\lib\site-packages\pyaedt\application\Analysis3D.py:78 in __init__
    Analysis.__init__(

  File C:\anaconda3\envs\spyder-pyaedt-env\lib\site-packages\pyaedt\application\Analysis.py:110 in __init__
    Design.__init__(

  File C:\anaconda3\envs\spyder-pyaedt-env\lib\site-packages\pyaedt\application\Design.py:194 in __init__
    desktop = Desktop(

  File C:\anaconda3\envs\spyder-pyaedt-env\lib\site-packages\pyaedt\desktop.py:567 in __init__
    self._init_desktop(non_graphical)

  File C:\anaconda3\envs\spyder-pyaedt-env\lib\site-packages\pyaedt\desktop.py:690 in _init_desktop
    self._main.AEDTVersion = self._main.oDesktop.GetVersion()[0:6]

AttributeError: module '__main__' has no attribute 'oDesktop'
```
To me, this looks like a file pathing issue. Also, when ChatGPT is asked about the error, it agrees that there is an issue with the path of the Ansys executable file.

From my question in the Q&A section, it was suggested that the student version could be called out with:
`app = pyaedt.Hfss(student_version=True)`
However, this produces the same error as before.

Other steps I have taken to try and fix the problem include:

1. Verifying that the installation path for Ansys is correct as is called out in the error.
2. Updating the PATH environment variable in Windows by adding the Ansys installation path to the Windows system PATH environment variable, which should allow the system to find the Ansys executable when called.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

aiohttp @ file:///D:/bld/aiohttp_1676292870197/work
aiosignal @ file:///home/conda/feedstock_root/build_artifacts/aiosignal_1667935791922/work
alabaster @ file:///home/conda/feedstock_root/build_artifacts/alabaster_1673645646525/work
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1666191106763/work/dist
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1640817743617/work
argon2-cffi-bindings @ file:///D:/bld/argon2-cffi-bindings_1666850789170/work
arrow @ file:///home/conda/feedstock_root/build_artifacts/arrow_1662382474514/work
astroid @ file:///D:/bld/astroid_1682340158088/work
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1670263926556/work
async-timeout @ file:///home/conda/feedstock_root/build_artifacts/async-timeout_1640026696943/work
atomicwrites @ file:///home/conda/feedstock_root/build_artifacts/atomicwrites_1657325823582/work
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1671632566681/work
autopep8 @ file:///home/conda/feedstock_root/build_artifacts/autopep8_1677845287175/work
Babel @ file:///home/conda/feedstock_root/build_artifacts/babel_1677767029043/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
bcrypt @ file:///D:/bld/bcrypt_1666831293551/work
beautifulsoup4 @ file:///home/conda/feedstock_root/build_artifacts/beautifulsoup4_1680888073205/work
binaryornot==0.4.4
black @ file:///D:/bld/black-recipe_1682492150929/work
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1674535352125/work
brotlipy @ file:///D:/bld/brotlipy_1666764804378/work
certifi==2022.12.7
cffi @ file:///D:/bld/cffi_1671179506518/work
chardet @ file:///D:/bld/chardet_1669990505384/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1661170624537/work
click @ file:///D:/bld/click_1666798499870/work
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1674202310934/work
clr-loader @ file:///home/conda/feedstock_root/build_artifacts/clr_loader_1672783374438/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1679481329611/work
contourpy @ file:///D:/bld/contourpy_1673633923174/work
cookiecutter @ file:///home/conda/feedstock_root/build_artifacts/cookiecutter_1654122127219/work
cryptography @ file:///D:/bld/cryptography-split_1681508778756/work
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
debugpy @ file:///D:/bld/debugpy_1680755654494/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
diff-match-patch @ file:///home/conda/feedstock_root/build_artifacts/diff-match-patch_1594679019945/work
dill @ file:///home/conda/feedstock_root/build_artifacts/dill_1666603105584/work
docstring-to-markdown @ file:///home/conda/feedstock_root/build_artifacts/docstring-to-markdown_1679424273982/work
docutils @ file:///D:/bld/docutils_1666755081246/work
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1643888246732/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1667317341051/work
fastjsonschema @ file:///home/conda/feedstock_root/build_artifacts/python-fastjsonschema_1677336799617/work/dist
flake8 @ file:///home/conda/feedstock_root/build_artifacts/flake8_1669396691980/work
flit_core @ file:///home/conda/feedstock_root/build_artifacts/flit-core_1667734568827/work/source/flit_core
fonttools @ file:///D:/bld/fonttools_1680021368967/work
frozenlist @ file:///D:/bld/frozenlist_1667935541751/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
imageio @ file:///home/conda/feedstock_root/build_artifacts/imageio_1682319100511/work
imagesize @ file:///home/conda/feedstock_root/build_artifacts/imagesize_1656939531508/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1682176699712/work
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1676919000169/work
inflection @ file:///home/conda/feedstock_root/build_artifacts/inflection_1598089801258/work
intervaltree==3.0.2
ipykernel @ file:///D:/bld/ipykernel_1679336472934/work
ipython @ file:///D:/bld/ipython_1680185618122/work
ipython-genutils==0.2.0
ipywidgets @ file:///home/conda/feedstock_root/build_artifacts/ipywidgets_1680023138361/work
isort @ file:///home/conda/feedstock_root/build_artifacts/isort_1675033873689/work
jaraco.classes @ file:///home/conda/feedstock_root/build_artifacts/jaraco.classes_1667024629799/work
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1669134318875/work
jellyfish @ file:///D:/bld/jellyfish_1666945709644/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1654302431367/work
jinja2-time @ file:///home/conda/feedstock_root/build_artifacts/jinja2-time_1646750632133/work
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema-meta_1669810440410/work
jupyter @ file:///D:/bld/jupyter_1670249771420/work
jupyter-console @ file:///home/conda/feedstock_root/build_artifacts/jupyter_console_1678118109161/work
jupyter-events @ file:///home/conda/feedstock_root/build_artifacts/jupyter_events_1673559782596/work
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1681432441054/work
jupyter_core @ file:///D:/bld/jupyter_core_1678994400417/work
jupyter_server @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_1679073341944/work
jupyter_server_terminals @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_terminals_1673491454549/work
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1649936611996/work
jupyterlab-widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1680020489668/work
keyring @ file:///D:/bld/keyring_1671728520281/work
kiwisolver @ file:///D:/bld/kiwisolver_1666805768319/work
lazy-object-proxy @ file:///D:/bld/lazy-object-proxy_1672877929216/work
loguru @ file:///D:/bld/loguru_1681126322414/work
MarkupSafe @ file:///D:/bld/markupsafe_1674136027121/work
matplotlib @ file:///D:/bld/matplotlib-suite_1678135731316/work
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
mccabe @ file:///home/conda/feedstock_root/build_artifacts/mccabe_1643049622439/work
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1675771498296/work
more-itertools @ file:///home/conda/feedstock_root/build_artifacts/more-itertools_1677514956219/work
multidict @ file:///D:/bld/multidict_1672339572480/work
munkres==1.1.4
mypy-extensions @ file:///home/conda/feedstock_root/build_artifacts/mypy_extensions_1675543315189/work
nbclassic @ file:///home/conda/feedstock_root/build_artifacts/nbclassic_1682598306082/work
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1682452223743/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert-meta_1681137024412/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1679336765223/work
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1664684991461/work
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1680870634737/work
notebook_shim @ file:///home/conda/feedstock_root/build_artifacts/notebook-shim_1682360583588/work
numpy @ file:///D:/bld/numpy_1682210442656/work
numpydoc @ file:///home/conda/feedstock_root/build_artifacts/numpydoc_1665273484262/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1681337016113/work
pandas @ file:///D:/bld/pandas_1682331620477/work
pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
paramiko @ file:///home/conda/feedstock_root/build_artifacts/paramiko_1678741293886/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
pathspec @ file:///home/conda/feedstock_root/build_artifacts/pathspec_1678853982175/work
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1667297516076/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow @ file:///D:/bld/pillow_1680694757876/work
pkgutil_resolve_name @ file:///home/conda/feedstock_root/build_artifacts/pkgutil-resolve-name_1633981968097/work
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1682644429438/work
pluggy @ file:///home/conda/feedstock_root/build_artifacts/pluggy_1667232663820/work
plumbum @ file:///home/conda/feedstock_root/build_artifacts/plumbum_1672805300556/work
ply==3.11
pooch @ file:///home/conda/feedstock_root/build_artifacts/pooch_1679580333621/work
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1674535637125/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1677600924538/work
psutil @ file:///D:/bld/psutil_1681775154843/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
pyaedt @ file:///D:/bld/pyaedt_1682695222916/work
pycodestyle @ file:///home/conda/feedstock_root/build_artifacts/pycodestyle_1669306857274/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pydocstyle @ file:///home/conda/feedstock_root/build_artifacts/pydocstyle_1673997487070/work
pyflakes @ file:///home/conda/feedstock_root/build_artifacts/pyflakes_1669319921641/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1681904169130/work
pylint @ file:///home/conda/feedstock_root/build_artifacts/pylint_1682377695563/work
pylint-venv @ file:///home/conda/feedstock_root/build_artifacts/pylint-venv_1677228547421/work
pyls-spyder @ file:///home/conda/feedstock_root/build_artifacts/pyls-spyder_1619747398504/work
PyNaCl @ file:///D:/bld/pynacl_1666862759359/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1680037383858/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1652235407899/work
PyQt5==5.15.7
PyQt5-sip @ file:///D:/bld/pyqt-split_1674666795342/work/pyqt_sip
PyQtWebEngine==5.15.4
pyrsistent @ file:///D:/bld/pyrsistent_1672681663470/work
PySocks @ file:///D:/bld/pysocks_1661604991356/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-json-logger @ file:///home/conda/feedstock_root/build_artifacts/python-json-logger_1677079630776/work
python-lsp-black @ file:///home/conda/feedstock_root/build_artifacts/python-lsp-black_1649795569828/work
python-lsp-jsonrpc @ file:///home/conda/feedstock_root/build_artifacts/python-lsp-jsonrpc_1618530352985/work
python-lsp-server @ file:///home/conda/feedstock_root/build_artifacts/python-lsp-server-meta_1680545288995/work
python-slugify @ file:///home/conda/feedstock_root/build_artifacts/python-slugify_1677265108728/work
pythonnet @ file:///home/conda/feedstock_root/build_artifacts/pythonnet_1664615507415/work
pytoolconfig @ file:///home/conda/feedstock_root/build_artifacts/pytoolconfig_1675124745143/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1680088766131/work
pyvista @ file:///home/conda/feedstock_root/build_artifacts/pyvista_1679092213213/work
pywin32==304
pywin32-ctypes @ file:///D:/bld/pywin32-ctypes_1666760898350/work
pywinpty @ file:///D:/bld/pywinpty_1672753220564/work/target/wheels/pywinpty-2.0.10-cp310-none-win_amd64.whl
PyYAML @ file:///D:/bld/pyyaml_1666772550103/work
pyzmq @ file:///D:/bld/pyzmq_1679316999325/work
QDarkStyle @ file:///home/conda/feedstock_root/build_artifacts/qdarkstyle_1654095878638/work
qstylizer @ file:///home/conda/feedstock_root/build_artifacts/qstylizer_1662244505808/work/dist/qstylizer-0.2.2-py2.py3-none-any.whl
QtAwesome @ file:///home/conda/feedstock_root/build_artifacts/qtawesome_1678418951316/work
qtconsole @ file:///home/conda/feedstock_root/build_artifacts/qtconsole-base_1680543490292/work
QtPy @ file:///home/conda/feedstock_root/build_artifacts/qtpy_1680148448366/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1682535435083/work
rfc3339-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3339-validator_1638811747357/work
rfc3986-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3986-validator_1598024191506/work
rope @ file:///home/conda/feedstock_root/build_artifacts/rope_1674988456931/work
rpyc @ file:///home/conda/feedstock_root/build_artifacts/rpyc_1610420736758/work
Rtree @ file:///D:/bld/rtree_1666813330222/work
scooby @ file:///home/conda/feedstock_root/build_artifacts/scooby_1674625672250/work
Send2Trash @ file:///D:/bld/send2trash_1682601429724/work
sip @ file:///D:/bld/sip_1681995290987/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1662051266223/work
snowballstemmer @ file:///home/conda/feedstock_root/build_artifacts/snowballstemmer_1637143057757/work
sortedcontainers @ file:///home/conda/feedstock_root/build_artifacts/sortedcontainers_1621217038088/work
soupsieve @ file:///home/conda/feedstock_root/build_artifacts/soupsieve_1658207591808/work
Sphinx @ file:///home/conda/feedstock_root/build_artifacts/sphinx_1682421508339/work
sphinxcontrib-applehelp @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-applehelp_1674487779667/work
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-htmlhelp_1675256494457/work
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-serializinghtml_1649380998999/work
spyder @ file:///D:/bld/spyder_1680729330943/work
spyder-kernels @ file:///D:/bld/spyder-kernels_1680544940746/work
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
terminado @ file:///D:/bld/terminado_1652790796353/work
text-unidecode==1.3
textdistance @ file:///home/conda/feedstock_root/build_artifacts/textdistance_1663527496115/work
three-merge @ file:///home/conda/feedstock_root/build_artifacts/three-merge_1595515817927/work
tinycss2 @ file:///home/conda/feedstock_root/build_artifacts/tinycss2_1666100256010/work
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1604308577558/work
tomli @ file:///home/conda/feedstock_root/build_artifacts/tomli_1644342247877/work
tomlkit @ file:///home/conda/feedstock_root/build_artifacts/tomlkit_1679924068997/work
tornado @ file:///D:/bld/tornado_1681817664954/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1675110562325/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1678559861143/work
tzdata @ file:///home/conda/feedstock_root/build_artifacts/python-tzdata_1680081134351/work
ujson @ file:///D:/bld/ujson_1675192160047/work
unicodedata2 @ file:///D:/bld/unicodedata2_1667239969015/work
Unidecode @ file:///home/conda/feedstock_root/build_artifacts/unidecode_1664588179651/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1678635778344/work
vtk==9.2.6
watchdog @ file:///D:/bld/watchdog_1679333145497/work
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1673864653149/work
webencodings==0.5.1
websocket-client @ file:///home/conda/feedstock_root/build_artifacts/websocket-client_1675567828044/work
whatthepatch @ file:///home/conda/feedstock_root/build_artifacts/whatthepatch_1675090462655/work
widgetsnbextension @ file:///home/conda/feedstock_root/build_artifacts/widgetsnbextension_1680021576815/work
win-inet-pton @ file:///D:/bld/win_inet_pton_1667051142467/work
win32-setctime @ file:///home/conda/feedstock_root/build_artifacts/win32_setctime_1642883564726/work
wrapt @ file:///D:/bld/wrapt_1677485718477/work
wslink @ file:///home/conda/feedstock_root/build_artifacts/wslink_1676499749829/work
yapf @ file:///home/conda/feedstock_root/build_artifacts/yapf_1641487982943/work
yarl @ file:///D:/bld/yarl_1682426748506/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1677313463193/work

**Comment by maxcapodi78** [comment]
@RaisinO  which Student version have you installed? 
have you tried rebooting machine to let environment variables being recognized after AEDT SV is installed?
Can you check that in your environment variables there is one named ANSYSEMSV_ROOT_xxx ?

**Comment by RaisinO** [comment]
@maxcapodi78 Thanks for the reply.
The student version installed is Ansys Electronics Desktop Student 2022 R2
A reboot has been performed after the installation of AEDT SV and after adding "C:\Program Files\AnsysEM\Ansys Student\v222\Win64" manually to the Windows PATH variable
Under environment variables there is ANSYSEMSV_ROOT222 with the correct install path of "C:\Program Files\AnsysEM\Ansys Student\v222\Win64"

**Comment by maxcapodi78** [comment]
@RaisinO I think I've figured out the issue. Give it a try in next Pyaedt Version 0.6.74 that I'll publish later this week

**Comment by RaisinO** [comment]
@maxcapodi78 It looks like the issue is fixed! I had to reset the Spyder IDE before it would work with the library correctly and call out the student version. Here is the result from the Spyder IPython console:
```
import pyaedt

app = pyaedt.Hfss(student_version=True, non_graphical=True)
app.release_desktop()
pyaedt INFO: using existing logger.
pyaedt INFO: Launching PyAEDT outside AEDT with CPython and PythonNET.
pyaedt INFO: AEDT installation Path C:\Program Files\AnsysEM\Ansys Student\v222\Win64.
pyaedt INFO: Launching AEDT with module PythonNET.
pyaedt INFO: AEDT 2022.2SV Student version started with process ID 30524.
pyaedt INFO: pyaedt v0.6.74
pyaedt INFO: Python version 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:00:38) [MSC v.1934 64 bit (AMD64)]
pyaedt INFO: AEDT 2022.2.0 Build Date 2022-05-26 22:06:26
pyaedt INFO: No project is defined. Project Project4 exists and has been read.
pyaedt INFO: No design is present. Inserting a new design.
pyaedt INFO: Added design 'HFSS_NWL' of type HFSS.
pyaedt INFO: Aedt Objects initialized
pyaedt INFO: Variable Manager initialized
pyaedt INFO: Design Loaded
pyaedt INFO: Materials Loaded
pyaedt INFO: Failed in Adding Desktop Message
pyaedt INFO: Project files removed from handlers.
Out[1]: True
```
Thanks so much.

**Comment by MaxJPRey** [comment]
Thanks @RaisinO for the confirmation that the bug was fixed.
