### ISSUE TITLE
Default version of AEDT to 19.3 

### ISSUE THREAD

**Issue by jleonatti** [pyansys/PyAEDT#305]
https://github.com/pyansys/PyAEDT/blob/d049964c5a20e81ed066bf82133789beef13b965/pyaedt/desktop.py#L101-L103

The update_aedt_registry method sets the default version of AEDT to 19.3 if one is not specified in the method call. Should this be upgraded to a newer version? Is 19.3 still even supported?

**Comment by maxcapodi78** [comment]
Default version has to be 2021R1 (211)

**Comment by jleonatti** [comment]
@maxcapodi78 I can change this. Thanks!

**Comment by maxcapodi78** [comment]
Thank you 👍

**Comment by jleonatti** [comment]
Fixed in PR. Closing.
