### ISSUE TITLE
Expliticilty versus explicitly

### ISSUE THREAD

**Issue by PipKat** [pyansys/PyAEDT#320]
In modeler.py, we have the method explicitiyly_subtract that but explicitiyly is misspelled. It should be explicitly.

**Comment by akaszynski** [comment]
@MaxJPRey, please create a PR to refactor this.  See:
https://github.com/pyansys/PyAEDT/blob/df5513fe7c3fa2afedbe08ce5b7e465cb3263041/pyaedt/modeler/Modeler.py#L2776

Don't bother with a deprecation warning or directive.
