### ISSUE TITLE
analyse versus analyze

### ISSUE THREAD

**Issue by PipKat** [pyansys/PyAEDT#333]
In hfss.py (and likely other files), some methods use analyse_ and others use analyze_. We should always use analyze as we are to use American spellings. Also, in hfss.py, we are missing an "in" in assign in this method: assig_voltage_source_to_sheet

**Comment by akaszynski** [comment]
@MaxJPRey, please rename `assig_voltage_source_to_sheet` to `assign_voltage_source_to_sheet`:
https://github.com/pyansys/PyAEDT/blob/130ecc7f80c648a7d3eb2606e8c9d8ce9e1b89ed/pyaedt/hfss.py#L1712

Additionally, create a separate PR with an `analyse --> analyze` refactor.

**Comment by maxcapodi78** [comment]
I agree. Please make sure that Examples are corrected accordingly

**Comment by MaxJPRey** [comment]
@maxcapodi78 Sure, I will check the examples.

**Comment by MaxJPRey** [comment]
@akaszynski I created a separate issue regarding the renaming of `assig_voltage_source_to_sheet `to `assign_voltage_source_to_sheet`.
See #342
