### ISSUE TITLE
Assigning design variable to parameter "amplitude" Maxwell2d.assign_current() does not work.

### ISSUE THREAD

**Issue by ganett** [pyansys/pyaedt#367]
Running the following line of code runs successfully: 

`m2d = Maxwell2d(designname=design_name, NG=True, solution_type=solution)
m2d.modeler.model_units = "mm"
current_boundary = m2d.assign_current([coil], amplitude=10, phase="0deg", solid=True, swap_direction=False, name="Current1").
`

A current condition on the coil object is created with an amplitude of 10A. However, when a an existing design variable is assigned to the amplitude parameter, the code runs but the variable is not assigned to the current condition.

`m2d["I1"] = "10A"
current_boundary = m2d.assign_current([coil], amplitude="I1", phase="0deg", solid=True, swap_direction=False, name="Current1")`

No exception or error is caught.

A reference code is attached in this issue.
[PyAEDT_M2D_DesignVariable_AssignCurrent.zip](https://github.com/pyansys/PyAEDT/files/6925081/PyAEDT_M2D_DesignVariable_AssignCurrent.zip)
[PyAEDT_M2D_DesignVariable_AssignCurrent.txt](https://github.com/pyansys/PyAEDT/files/6925085/PyAEDT_M2D_DesignVariable_AssignCurrent.txt)

Thanks and best regards
ganett

**Comment by maxcapodi78** [comment]
Hello,
I've fixed it in #548
