### ISSUE TITLE
function Maxwell2d.assign_current does not work on Magnetostatic solver

### ISSUE THREAD

**Issue by tizianrot** [pyansys/pyaedt#371]
Hallo,

since it asks for a phase, that function is not accepted by the Magnetostatic solver. I could find an equivalent function performing the job, so I relied on the old APIs as follows:
```py
my_current_list = [
		"NAME:Current1",
		"Objects:="		, ["Rectangle1"],
		"Current:="		, "1A",
		"IsPositive:="		, True
	]

my_omodule = m2d.odesign.GetModule("BoundarySetup")
my_omodule.AssignCurrent(my_current_list)
```
Thank you,
Tiziana

**Comment by akaszynski** [comment]
Looks like we need to add this method.  @maxcapodi78, let's add this as a feature.

@tizianrot, if you'd like, you can submit a pull request adding this feature to the appropriate class.  Please ping me if you need any pointers.
