### ISSUE TITLE
unwanted prefix in source/sink names

### ISSUE THREAD

**Issue by ring630** [pyansys/PyAEDT#380]
When source name is defined as below
self.edbapp.core_siwave.create_voltage_source("U2A5","V1P5_S3","U2A5","GND",3.3,0, **source_name="U2A5-V1P5_S3"**)

The actual source name created is **V1P5_S3**_U2A5-V1P5_S3. 

create_voltage_source() automatically adds net name as prefiex. It is desired to be able to remove the prefix.

create_current_source() has the same issue

**Comment by ring630** [comment]
Fixed.

**Comment by akaszynski** [comment]
Which PR was this fixed in?
