### ISSUE TITLE
closing project closes application

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [pyansys/pyaedt#381]
To reproduce 

1. Start AEDT 21.2 manually.
2. Launch a Python kernel and create an instance of an Hfss() app.
3. Insert a new project/design
4. Close the HFSS project without saving it
-> The AEDT desktop closes.

**Comment by maxcapodi78** [comment]
Not an issue. There is a way to release the desktop without closing the Desktop
app.release_desktop(False, False)
