### ISSUE TITLE
No method is accessible in class edb.Cell

### ISSUE THREAD

**Issue by ring630** [pyansys/PyAEDT#385]
Reproduce the problem by below code
```
import clr

clr.AddReference('System.Xml')
from pyaedt.edb import Edb

aedb_path = "Galileo.aedb"
edb = Edb(edbpath=aedb_path, edbversion="2021.1")
edb.edb.Cell.Create()
```

```
Traceback (most recent call last):
  File "C:/Users/hzhou/AppData/Roaming/JetBrains/PyCharmCE2020.1/scratches/json_test.py", line 10, in <module>
    edb.edb.Cell.Create()
AttributeError: Create
```

**Comment by maxcapodi78** [comment]
I would suggest to try using:
 edb.edb.Cell.Create(edb.db,  edb.edb.Cell.CellType.CircuitCell, "MyNewCell")

**Comment by ring630** [comment]
> I would suggest to try using:
> edb.edb.Cell.Create(edb.db, edb.edb.Cell.CellType.CircuitCell, "MyNewCell")

I still get this error

Traceback (most recent call last):
  File "C:/Users/hzhou/AppData/Roaming/JetBrains/PyCharmCE2020.1/scratches/scratch.py", line 8, in <module>
    edb.edb.Cell.Create(edb.db, edb.edb.Cell.CellType.CircuitCell, "MyNewCell")
AttributeError: Create

**Comment by maxcapodi78** [comment]
it is because you are missing one level
the right command should be (with two Cell levels)

edb.edb.Cell.Cell.Create(edb.db, edb.edb.Cell.CellType.CircuitCell, "MyNewCell")

**Comment by maxcapodi78** [comment]
Anyway we may add a create_cell method in Edb Class

**Comment by maxcapodi78** [comment]
@ring630 can you close this issue since my last comment worked for you?

**Comment by ring630** [comment]
Thanks!
