### ISSUE TITLE
Incorrect arguments paseed in GeometryModeler.create_group()

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [pyansys/PyAEDT#391]
When passing arguments to oeditor.CreateGroup() the list of objects need to be passed as "SubmodelInstance:=" instead of "Parts:=".  I found this in 2021R2 and have a branch called "microdoppler_updates" where this has been fixed.  I'm updating this branch to support the micro-doppler demo created by Arien and Ushe.

**Comment by maxcapodi78** [comment]
The argument is correct for objects but incorrect for 3DComponents. I've modified the methods input arguments to support also 3dcomponent list as input.
