### ISSUE TITLE
Can assign_winding func define whether the winding's stranded or solid?

### ISSUE THREAD

**Issue by Javpyer** [pyansys/PyAEDT#392]
We are unable to use assign_winding function to define the winding's "IsSolid" property right? How can we define if the winding is stranded or solid? Thanks

**Comment by maxcapodi78** [comment]
I've added a new input parameter to assign_winding method. is called is_solid and its default value is True.
Anyway, in the future, any boundary you create wit Pyaedt returns you a Boundary object. so you could always do the following:
mybound=aedtapp.assign_winding()
mybound.props["IsSolid"]=False
mybound.update()

this allows the user to modify properties even if they are not mapped by default.
