### ISSUE TITLE
Numpydoc validation

### ISSUE THREAD

**Issue by jleonatti** [pyansys/pyaedt#424]
Add the following [directives](https://numpydoc.readthedocs.io/en/latest/validation.html#built-in-validation-checks) to the validation configuration:
- [ ] RT05 - Return value description should finish with "."
- [ ] ...

**Comment by Samuelopez-ansys** [comment]
Hi @CollinHough , @jleonatti ,

Is this issue still in progress?

Thanks

**Comment by jleonatti** [comment]
Hi @Samuelopez-ansys, I no longer directly contribute to this project, so there has not been any work related to this issue from me.

**Comment by MaxJPRey** [comment]
@Samuelopez-ansys I will add the directive suggested by @jleonatti .
We already have some of them checked.

**Comment by Samuelopez-ansys** [comment]
@MaxJPRey Is this issue fixed?
