### ISSUE TITLE
DCIR setup is removed after cutout and cannot be added.

### ISSUE THREAD

**Issue by ring630** [pyansys/pyaedt#427]
appedb = Edb(edbpath="Galileo.aedb", edbversion="2021.2")

settings = appedb.core_siwave.get_siwave_dc_setup_template()
appedb.core_siwave.add_siwave_dc_analysis()
appedb.save_edb_as("full_board.aedb")
 # **Save the full board with dc analysis. Everything is fine here.**

appedb.create_cutout(["A0_N", "A0_P"], ["GND"])
appedb.save_edb_as("cutout.aedb")
# **After cutout, the dc analysis is gone.**

appedb.core_siwave.add_siwave_dc_analysis()
appedb.save_edb_as("cut_out_add_DC_again.aedb")
# **DC analysis cannot be added in the cutout design**

**Comment by maxcapodi78** [comment]
@ring630 @MaxJPRey Fixed in #704

**Comment by ring630** [comment]
@maxcapodi78 I confirm it is fixed.
