### ISSUE TITLE
Maxwell2D->Master/Slave

### ISSUE THREAD

**Issue by Javpyer** [pyansys/pyaedt#429]
How can I set the Master/Slave boundaries in Maxwell2D? I'm not finding corresponding API Document. Thanks!

**Comment by Zwl20085** [comment]
> How can I set the Master/Slave boundaries in Maxwell2D? I'm not finding corresponding API Document. Thanks!

I think you can access the corresponding function through com object of AEDT (maxwell2d.oeditor or maxwell2d.odesign ). you can find the name of the function to set master/slave in <<maxwell scripting.pdf>>, which is stored in AEDT if you have installed in local help.

**Comment by maxcapodi78** [comment]
It's not there yet. I'll put in the backlog of new feature

**Comment by maxcapodi78** [comment]
@Zwl20085  you are right. any function not wrapped by pyaedt is accessible through the oeditor or odesign object.

**Comment by maxcapodi78** [comment]
@Javpyer  assign_master_slave method is now in #453
