### ISSUE TITLE
Make call signatures consistent in Primitives3D

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [pyansys/pyaedt#490]
The csPlane call signature and default values for create_rectangle() and create_cylinder() are inconsistent and confusing. Should be refactored. Can probably be done without impacting existing scripts.

**Comment by MaxJPRey** [comment]
@dcrawforAtAnsys With the work done in the PR #568 and the introduction of the constants, I think that the descriptions for the csplane and cs_axis are more consistent. Is it correcting the inconsistency that you pointed out?
