### ISSUE TITLE
load_entire_aedt_file parsing issue

### ISSUE THREAD

**Issue by beliaev-maksim** [pyansys/pyaedt#560]
data in curves is not properly parsed into dictionary, see  [Loss Plot 1_NBXOYK.rdat](https://github.com/pyansys/pyaedt/files/7508088/Loss.Plot.1_NBXOYK.rdat.txt)

reproduce via 
```python
from pyaedt.generic.LoadAEDTFile import load_entire_aedt_file
data = load_entire_aedt_file(file_path)
print(data["ReportsData"]["RepMgrRepsData"]['Loss Plot 1']['Traces']["0"]['CurvesInfo'])
```
![image](https://user-images.githubusercontent.com/51964909/141007800-3baf6fcd-bc86-45e7-baa9-816f57ea67ed.png)

**Comment by beliaev-maksim** [comment]
@Alberto-DM , @maxcapodi78 
can you please have a look ?

**Comment by Alberto-DM** [comment]
I have fixed this in ADM_load_aedt_label_bug
