### ISSUE TITLE
Clean Stop / Abort Command in HFSS

### ISSUE THREAD

**Issue by tungnguyen1003** [pyansys/pyaedt#561]
Would anyone employ the code to execute Clean Stop or Abort command? Appreciate your help.

**Comment by maxcapodi78** [comment]
that would be though but I'll investigate.

**Comment by kbhagat-ansys** [comment]
I wonder how it would work. 
Currently if someone gives `oDesign.Analyze()` then that function only goes to the next script command when its completed. So when will user be able to do an Abort? This change might require development to step in and essentially allow a argument like `oDesign.Analyze(dont_wait_for_simulation_to_finish=True)` 

@maxcapodi78

**Comment by maxcapodi78** [comment]
this cannot implemented at this time since AEDT API doesn't support it

**Comment by svandenb-dev** [comment]
closing this issue as not supported by the API.
