### ISSUE TITLE
create_circle message error

### ISSUE THREAD

**Issue by cristianbabetto** [pyansys/pyaedt#588]
![error_pyaedt](https://user-images.githubusercontent.com/48283075/142185130-91243b24-8a20-4d93-85aa-eb8c49031742.png)
Good morning,

In Maxwell2d transient, when I use the command
`circ = m2d.modeler.primitives.create_circle([0,0,0], 20)
`
a circle is drawn but I get the following error messages:
`
*Global - Messages
  [info] pyaedt v0.2.23
  [info] Python version 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
PSA_ID_711_v2_ANSYSEM_2D (D:/AC_WINDING_LOSS_STUDY/MAXWELL/)
  Motor-CAD PSA_ID_711_v2 (Transient, XY)
    [error] Script macro error: Invalid PropServer 'NewObject_ZNCOWB'. (11:30:12  nov 17, 2021)
    [error] Script macro error: Invalid PropServer 'NewObject_ZNCOWB'. (11:30:12  nov 17, 2021)
`

**Comment by maxcapodi78** [comment]
@cristianbabetto Please update to latest version of pyaedt (0.4.8). That issue has been fixed from pyaedt 0.4.x

**Comment by cristianbabetto** [comment]
Ok thanks. Now it works.
