### ISSUE TITLE
Enable 'Maxwell3d.assign_current' Method to work with Magnetostatic Solver

### ISSUE THREAD

**Issue by DaveTwyman** [pyansys/pyaedt#619]
Unless I'm mistaken the titled method does not work with the magnetostatic solver
![image](https://user-images.githubusercontent.com/90868812/144508126-b0eea9ad-5e22-4d2d-b0e9-00a3c9b2857b.png)

**Comment by maxcapodi78** [comment]
@DaveTwyman I'm fixing it.
