### ISSUE TITLE
M2D.modeler.primitives.create_udp function does not assign name to the created object

### ISSUE THREAD

**Issue by tizianrot** [pyansys/pyaedt#647]
Dear All,

while using the function:

M2D.modeler.primitives.create_udp

the udp creates the desired object correctly but assigns automatically the udp default name. The optional parameter name is not used further in the function implementation (I saw obj_name is used and maybe this is the problem).

Also the function to rename objects is missing, analogous to the API:

oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:Geometry3DAttributeTab",
			[
				"NAME:PropServers", 
				"VentSlotCore"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:Name",
					"Value:="		, "Stator"
				]
			]
		]
	])

Thank you for your help,

Tiziana

**Comment by maxcapodi78** [comment]
Simply do 
my_udp.name = "myname" 
after you create the udp. It works.
