### ISSUE TITLE
The name of the net for the polygon creation must be improved.

### ISSUE THREAD

**Issue by MaxJPRey** [pyansys/pyaedt#660]
https://github.com/pyansys/pyaedt/blob/ddab51735aa50a41996d515657aecddfb776bc56/pyaedt/edb.py#L1039

**Comment by maxcapodi78** [comment]
@MaxJPRey  The name of the net has to be DUMMY_XXX. this is managed differently by the solver from a different naming. you cannot change it in with POLYGON_XXX
