### ISSUE TITLE
There is no HFSS API supporting Multiple Sweep Range

### ISSUE THREAD

**Issue by linmingchih** [pyansys/pyaedt#677]
![2021-12-25_19-55-22](https://user-images.githubusercontent.com/13580731/147384408-c48b3b6e-d5fb-4e94-a044-8d3dff9d8233.png)

**Comment by MaxJPRey** [comment]
Hi @linmingchih,

I think you could add multiple sweep ranges with the following example for instance

```
Create a setup in an HFSS design and add multiple sweep ranges.

setup = hfss.create_setup(setupname="MySetup")
sweep = setup.add_sweep()
sweep.change_type("Interpolating")
sweep.change_range("LinearStep", 1.1, 2.1, 0.4, "GHz")
sweep.add_subrange("LinearCount", 1, 1.5, 5, "MHz")
sweep.add_subrange("LogScale", 1, 3, 10, "GHz"):
```
I will add this example in the add_subrange() method docstring.

Thanks.
