### ISSUE TITLE
Optimetrics Calculations Support

### ISSUE THREAD

**Issue by DaveTwyman** [pyansys/pyaedt#728]
When opening a design with Optimetrics Calculations added, the below error messages appear
![AEDT_Errors1](https://user-images.githubusercontent.com/90868812/149938683-5071d18f-6925-4cf8-8c3d-dc9e6514a8d4.png)
![AEDT_Errors2](https://user-images.githubusercontent.com/90868812/149938728-32e27e7d-f1d9-4150-915e-62e7f37a9425.png)

Behavior can be recreated by running the attached script and model as shown below
![Script](https://user-images.githubusercontent.com/90868812/149938847-cdc3fa08-26ac-4539-829d-9a7ba0255161.png)

It seems like PyAEDT cannot support calculations at the moment
![OptCalc](https://user-images.githubusercontent.com/90868812/149940094-0bac609f-2a69-4f4c-90cc-57c28861e5b6.png)
[This_is_an AEDT_Project.txt](https://github.com/pyansys/pyaedt/files/7889142/This_is_an.AEDT_Project.txt)

**Comment by maxcapodi78** [comment]
Fixed #729

**Comment by DaveTwyman** [comment]
Brilliant, Thanks
