### ISSUE TITLE
Add Function to Create Wave Port in HFSS DriverTerminal with autoidentify() 

### ISSUE THREAD

**Issue by linmingchih** [pyansys/pyaedt#737]
Waveport creation in DrivenTerminal with autoidentify() is not supported yet in PyAEDT. Currently I use the code below instead:

def create_waveport(face_id, port_num="1", reference_names=[]):
    oModule.AutoIdentifyPorts(
    	[
    		"NAME:Faces", 
    		face_id
    	], True, 
    	[
    		"NAME:ReferenceConductors", 
    	] + reference_names, port_num, True)

If possible, please add this function in pyAEDT module, thanks.

![image](https://user-images.githubusercontent.com/13580731/150104937-b0eeb1b2-c72c-4bf3-b5e5-3daeb6c59b65.png)

**Comment by maxcapodi78** [comment]
Hi @linmingchih  it is. I've implemented in #738. I'm gonna create a package today which will contain also an example. The same works also for lumped port in driven terminal.
