### ISSUE TITLE
position_list doen't accept ["x1", "y1"]

### ISSUE THREAD

**Issue by ring630** [pyansys/pyaedt#741]
https://github.com/pyansys/pyaedt/blob/e422836bc7ebf98e2a7a416978ba8a6e11057d91/pyaedt/modeler/Primitives.py#L1305-L1310

It looks like the docstring is not correct. As I tested, this method doesn't accept 2-dimensional position_list ``["x1", "y1"]``.. Can someone confirm it?

**Comment by MaxJPRey** [comment]
@ring630 You are correct, the polyline must be defined using "x, y, z" coordinates even when providing a list of variables. I am modifying the documentation and example accordingly.
Thanks.
