### ISSUE TITLE
Add new Function: ModelerNexxim.connect()

### ISSUE THREAD

**Issue by linmingchih** [pyansys/pyaedt#744]
There is no function to connect multiple components in one node. Suggest a function like this:
circuit.modeler.components.connect(*args)
e.g.
circuit.modeler.components.connect_components(C1.pins[1], L1.pins[0], C2.pins[0])

**Comment by maxcapodi78** [comment]
@linmingchih this is already available. Try this: 

`
from pyaedt import Circuit
aedt_app = Circuit()
inductor = aedt_app.modeler.schematic.create_inductor("L1", 1e-9)
resistor = aedt_app.modeler.schematic.create_resistor("R1", 50)
capacitor = aedt_app.modeler.schematic.create_capacitor("C1", 1e-12)

inductor.pins[1].connect_to_component([resistor.pins[0], capacitor.pins[1]])
`
