### ISSUE TITLE
Bug in create_region with Maxwell2d / MagnetostaticZ

### ISSUE THREAD

**Issue by BLeistr** [pyansys/pyaedt#752]
When creating a region in Maxwell 2D cylindrical, the offset is realized only in R (X) direction and not in z direction. Here, only a "zero" is passed.
In Maxwell 3D and also 2D XY the error does not seem to occur.

Test code:
from pyaedt import Maxwell2d
m2d = Maxwell2d(solution_type="MagnetostaticZ")
magnet = m2d.modeler.primitives.create_rectangle([0, 0, 0], ["10mm", "5mm"], name="Box", matname="ndfe30")
region = m2d.modeler.primitives.create_region(200)

![grafik](https://user-images.githubusercontent.com/98037049/150495004-55a19f21-5d73-427b-b0dc-1f896cb11aaa.png)

**Comment by maxcapodi78** [comment]
Fixed in #763

**Comment by maxcapodi78** [comment]
Hello @BLeistr it has been added to new version 0.4.24
