### ISSUE TITLE
Parameter "axisdir"

### ISSUE THREAD

**Issue by PipKat** [pyansys/pyaedt#76]
The parameter "axisdir" descriptions do not always seem to be correct. For example, within the file HFSS.py, it is described as string with a default value of XYNE. However, most of the time, the function signature shows a default of 0. Alex indicated that this didn't seem to make sense and that you should look at it.
In one case, the description for "axisdir" is "Position of the VS."  What is VS. We should spell out abbreviations and acronyms or provide more hints if the terminology isn't well know. Alex said he thought VS might the voltage of a transistor's source terminal,  but he wasn't certain.

**Comment by MaxJPRey** [comment]
@maxcapodi78 I think we can close this issue.
You justified the first point regarding the enum default value set to an int.
Regarding "Position of the VS", it is not written into the hfss.py module anymore.
