### ISSUE TITLE
Maxwell Method missing: Set core Loss on

### ISSUE THREAD

**Issue by tizianrot** [pyansys/pyaedt#765]
Dear All,
in order to effectively simulate electric machines the abovementioned method is needed and I cannot find it. It would be analogous to M2D.eddy_effects_on

since in the GUI you can find them both under Excitations.
In this case:
Excitations-> set core loss
Thank you,
Tiziana

**Comment by maxcapodi78** [comment]
Fixed in #767

**Comment by maxcapodi78** [comment]
Added to v0.4.24
