### ISSUE TITLE
Project Properties are never updated once they have been set.

### ISSUE THREAD

**Issue by MaxJPRey** [pyansys/pyaedt#771]
Project properties are set when the project is saved but are not updated anymore after that when the user modifies some settings.
For instance, the `model_depth` for a maxwell 2D transient cannot be updated after the project has been saved.

The behavior of the property `project_properies` in `Design()` must be updated.

**Comment by Samuelopez-ansys** [comment]
Hi @MaxJPRey , is this issue fixed?

**Comment by maxcapodi78** [comment]
this has been fixed

**Comment by MaxJPRey** [comment]
Yes @Samuelopez-ansys it has been fixed. Thanks to you and @maxcapodi78 for closing it.
