### ISSUE TITLE
Add ODB++ Import Function in HFSS 3D Layout

### ISSUE THREAD

**Issue by linmingchih** [pyansys/pyaedt#774]
Can't Find ODB++ Import Function in Help

**Comment by maxcapodi78** [comment]
Actually you can do with Edb with following method. Once imported, you can save and close the edb and open the edb with Hfss3dLayout.
`
    def import_layout_pcb(self, input_file, working_dir, init_dlls=False, anstranslator_full_path="", use_ppe=False):
`

**Comment by maxcapodi78** [comment]
Even easier if to start Edb class directly passing the tgz file (the import layout will be automatically applied.

`
from pyaedt import Edb
edb = Edb("path/to/tgz", edbversion="2021.2")
edb.save_edb()
edb.close_edb()
from pyaedt import Hfss3dLayout
h3d =Hfss3dLayout("path/to/aedb/edb.def")

`

**Comment by linmingchih** [comment]
Thanks, It works well.
