### ISSUE TITLE
Deleting Icepak Surface Plot Fails

### ISSUE THREAD

**Issue by ansys-icepak** [pyansys/pyaedt#798]
This command fails:

ipk.post.delete_field_plot("Surface_Temps_Chassis")

But this one works just fine:

ipk.post.field_plots["Surface_Temps_Chassis"].delete()

Any test model should do, please let me know if you have any questions.

**Comment by maxcapodi78** [comment]
@ansys-icepak Fixed in #800

**Comment by ansys-icepak** [comment]
@maxcapodi78 working great now, thanks!
