### ISSUE TITLE
Assign Icepak Mesh Region is Failing in 2022 R2

### ISSUE THREAD

**Issue by ansys-icepak** [pyansys/pyaedt#816]
Hi, 

This was working fine before, but after I updated AEDT 2022 R2, this method is now failing.   A few snapshots are attached.  Could you please take a look and let me know? 

Thanks,
Best,
Carlos

![image](https://user-images.githubusercontent.com/97304143/152382603-bdd9e815-3b31-416a-913a-4e2d91ab6bd6.png)

![image](https://user-images.githubusercontent.com/97304143/152382719-197cce3d-383e-4f22-b7f9-e19a2b037309.png)

![image](https://user-images.githubusercontent.com/97304143/152382764-39c8ba26-26f0-4a91-888f-8386eb8dc501.png)

**Comment by ansys-icepak** [comment]
@maxcapodi78 

Hi Massimo, looks like this is still failing in 22 R2.  Have you had a chance to take a look?

**Comment by maxcapodi78** [comment]
Hi @ansys-icepak  Have you checked in latest pyaedt version this method? I've added new API settings to be compatible with 22R2 some weeks ago

**Comment by Samuelopez-ansys** [comment]
Hi @ansys-icepak ,

Please could you check if the issue is still there? If it works please close the issue.
