### ISSUE TITLE
Cosmetic Solution Type Error Message

### ISSUE THREAD

**Issue by ansys-icepak** [pyansys/pyaedt#817]
After updating to the latest development pyAEDT, I now get this seemingly cosmetic error message.  Maybe we can suppress this error or handle it more gracefully?

![image](https://user-images.githubusercontent.com/97304143/152383358-086225d7-5b61-4cd3-92d6-8fc4571bd74b.png)

**Comment by ansys-icepak** [comment]
Forgot to mention, this is for AEDT Icepak.

**Comment by maxcapodi78** [comment]
I'll check. Please let me know on which version of AEDT you get it.

**Comment by ansys-icepak** [comment]
Happens for both 2022 R1 and R2.  Haven't tested previous versions.

**Comment by maxcapodi78** [comment]
@ansys-icepak can you check if the problem is still there? it happens when you create a new Icepak or when you open an existing project?
