### ISSUE TITLE
Add function to add edge port for R/L/C in HFSS 3D Layout

### ISSUE THREAD

**Issue by linmingchih** [pyansys/pyaedt#829]
![image](https://user-images.githubusercontent.com/13580731/152628277-740f0eda-8a91-4bb3-b5e0-dd6bf2446dac.png)

**Comment by maxcapodi78** [comment]
@MaxJPRey  maybe @linmingchih  wants to have an automatic way to replace a R/L/C with an edge port. Is it this the case?

**Comment by ring630** [comment]
@linmingchih @MaxJPRey @maxcapodi78 , if circuit port is acceptable, add_port_on_rlc_component() places a circuit port on the RLC component.
