### ISSUE TITLE
edb.core_components.set_solder_ball() failed in Other type component

### ISSUE THREAD

**Issue by linmingchih** [pyansys/pyaedt#831]
It works for "IC" type component, but failed in "Other" type component:
---------------------------------------------------------------------------------------------------
Method set_solder_ball Failed:  Type Error. Please Check again
No method matches given arguments for SetComponentProperty: (<class 'Ansys.Ansoft.Edb.Cell.Hierarchy.PortProperty'>)
Arguments Provided: 
    component = RCON12 
    sball_diam = None 
    sball_height = 100um 
Error in :   File "d:\my_venv3\lib\site-packages\pyaedt\edb_core\components.py", line 1074, in set_solder_ball
Check Online documentation on: https://aedtdocs.pyansys.com/search.html?q=set_solder_ball
Method set_solder_ball Failed:  Type Error. Please Check again
No method matches given arguments for SetComponentProperty: (<class 'Ansys.Ansoft.Edb.Cell.Hierarchy.PortProperty'>)
Arguments Provided: 
    component = RCON12 
    sball_diam = 0.0007999984 
    sball_height = 0.0007999984 
Error in :   File "d:\my_venv3\lib\site-packages\pyaedt\edb_core\components.py", line 1074, in set_solder_ball
Check Online documentation on: https://aedtdocs.pyansys.com/search.html?q=set_solder_ball

**Comment by svandenb-dev** [comment]
Hi @linmingchih,
did you tried with the latest Pyaedt version ? I am trying to reproduce the error but actually it is working as expected. We worked couple of weeks ago on this part and I think this issue was fixed. 
Could you please test again and confirm ?
thanks a lot for your feedback
