### ISSUE TITLE
How to assign the material not in "[sys]Materials" library ?

### ISSUE THREAD

**Issue by Siderpan** [pyansys/pyaedt#846]
Hi,

I'm try to assign the material not in ```[sys]Materials``` .
```
m2d.assign_material('Stator', '35CS550')
```
If I just type the name that I want , It well search the whole library and pop out the error 
![image](https://user-images.githubusercontent.com/89152981/153356281-7a258278-3876-4f89-855a-07d374db9991.png)
Is there something that I misunderstood or wrong type?
And after solving this problem I also want to change the material's parameters , like change ```Composition``` parameter from ```Solid``` to  ```Lamination```.
![image](https://user-images.githubusercontent.com/89152981/153357314-1318c72b-e5b5-4fac-b1d9-0985f66602ae.png)

Thanks a lot,
Best regards,
Jason.

**Comment by maxcapodi78** [comment]
Hi Jason, where is located your material?

**Comment by maxcapodi78** [comment]
I've checked and if I've a material saved in an amat file in personallib folder it is correctly retrieved. I've also checked with a granta material and worked as well. Make sure that the material name you add  is correct. In your screenshot "China Steel - 50CS600" and not simply "50CS600"

**Comment by Siderpan** [comment]
Hi,
Thanks for your reply. I found that my problem came from using the  old version(2020R2). 
This function works fine when I change the version to 2021R1.

Thank you so much for taking the time to help solve the problem.
Best regards,
Jason

**Comment by Alberto-DM** [comment]
As the problem has been solved, I close this issue.
