### ISSUE TITLE
Improve handling of UDPs

### ISSUE THREAD

**Issue by JuliusSaitz** [pyansys/pyaedt#847]
Some suggestions:

1) udp_parameters_list is a required parameter. If none is specified, there is an error. I suggest that this is not required and in case none is specified, the default parameters are used. Currently, if at least one is specified, it works OK.  

2) Remove "name" from the input parameters, as it anyway does not work. The name can be changed later by using UDP.name.

3) Correct the spelling for udp_type parameter. It is written as udptye.

4) Currently, once a UDP is created, there is no way (at least I could not find) to change the UDP parameters. The only way would be use the original API, that is:
```
oEditor=UDP.m_Editor
oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:Geometry3DCmdTab",
			[
				"NAME:PropServers",
				"rotor:CreateUserDefinedPart:1"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:InfoCore",
					"Value:="		, "1"
				]
			]
		]
	])
```
So there is a workaround, but if there is a way to improve this and access the parameters directly, like UDP.InfoCore, that would be great.

**Comment by MaxJPRey** [comment]
@JuliusSaitz A new method named `update_udp` has been added.

**Comment by MaxJPRey** [comment]
@JuliusSaitz Regarding your feedback from the argument `Name` not having any impact, it should work.
Here is a short example:
```
        my_udpName = "MyClawPoleCore"
        udp = self.aedtapp.modeler.create_udp(
            udp_dll_name="RMxprt/ClawPoleCore",
            udp_parameters_list=my_udpPairs,
            upd_library="syslib",
            name=my_udpName,
            udptye="Solid",
        )

        assert udp
        assert udp.name == "MyClawPoleCore"
```
