### ISSUE TITLE
When creating components in Circuit, command a complete complete feature would be helpful to get library syntax correct.

### ISSUE THREAD

**Issue by cmesibov** [pyansys/pyaedt#860]
I am trying to add a LISN to my schematic using:
lisn = circuit.modeler.schematic.create_component(component_library=r'EMC_Tools\Line Impedance Stabilization Networks',component_name='LISN:CISPR25_LISN')
But aedt is giving errors, basically can't find the component.
It would be helpful if pyaedt had the Nexim directory locations stored so a command complete would make the code generation smoother.
I would have tagged this as an enhancement request, but I don't know how to do that in this editor.
Chris

**Comment by maxcapodi78** [comment]
Added in #865
