### ISSUE TITLE
How to change object orientation in maxwell2d ?

### ISSUE THREAD

**Issue by tako861225** [pyansys/pyaedt#869]
Hi ~ 
I would like to change the the ```Orientation``` from ```Global``` to ```Magnetcs1``` .
Just like the pic below
![未命名](https://user-images.githubusercontent.com/51187903/154449194-4210d6c8-b4fb-4938-bf7a-45a2657e48da.png)
I search the API but I still can't find the relative solution to fix the problem QQ.

thanks a lot,
Evelyn.

**Comment by maxcapodi78** [comment]
you can change it by using object property getter and setters
Example
Getter
print(m3d.modeler["Magnet"].part_coordinate_system)
Setter
m3d.modeler["Magnet"].part_coordinate_system = "magnetcs1"
