### ISSUE TITLE
Get the Same Letter Cases of Material Names Defined in Project

### ISSUE THREAD

**Issue by linmingchih** [pyansys/pyaedt#875]
[i.material_name for i in hfss.modeler.object_list] return materials in lower cases even the material name contains upper cases. When I use the name to assign new objects, there will be two categories in the object tree as shown in the figure below. It is confusing.

![image](https://user-images.githubusercontent.com/13580731/154617998-7945b9e2-b6b1-4570-a067-ac06d2ac8afc.png)

**Comment by maxcapodi78** [comment]
Hi @linmingchih I'll check into it. The problem is that AEDT is sometimes case insensitive and sometimes case sensitive to material names.

**Comment by maxcapodi78** [comment]
@linmingchih this looks a bug since Material Manager is case insensitive. Can you submit a bug to our Dev Team?

**Comment by Samuelopez-ansys** [comment]
@maxcapodi78  This is already fixed, right?
