### ISSUE TITLE
launch_ironpython_server results in no keyboard echo after server is launched

### ISSUE THREAD

**Issue by isaacansys** [pyansys/pyaedt#929]
Using CPython 3.6 on CentOS 7.9.2009, launch_ironpython_server works and returns a working client object but there is no keyboard echo making interactive usage very difficult.  Also observed on another machine with CPython 3.8, OS revision unknown.

**Comment by MaxJPRey** [comment]
@isaacansys Is it still happening with the new version v0.5.0. (or newer)? With the new support of CPython on Linux it should work properly.

**Comment by isaacansys** [comment]
@MaxJPRey it does not occur in a quick test using CPython 3.7.  I think we can close this as obsolete.

**Comment by MaxJPRey** [comment]
@isaacansys Thanks for the feedback. Yes it should be fixed.
