### ISSUE TITLE
Support dictionary type argument in hfss.edit_source()

### ISSUE THREAD

**Issue by linmingchih** [pyansys/pyaedt#931]
hfss.edit_source() supports one port only, If I want to change the power of 64 ports, I need to change one by one. it loads data for every change. it wastes time. the classical API EditSources() allows power change of all excitations at once.

example code

        import matplotlib.pyplot as plt
        from pyaedt import Hfss
        hfss = Hfss(specified_version='2022.1')
        
        def myedit_source(self, excitations):
            data = {i:('0W', '0deg') for i in self.excitations}
            for key, value in excitations.items():
                data[key] = value
            
            setting = []
            for key, (power, phase) in data.items():
                setting.append(["Name:=", key, "Magnitude:=", power, "Phase:=", phase])
            
            argument = ["IncludePortPostProcessing:=", True, "SpecifySystemPower:=", False]
            self.osolution.EditSources([argument,] + setting)
        
        setattr(hfss, 'myedit_source', lambda v: myedit_source(hfss, v))

**Comment by maxcapodi78** [comment]
A new method edit_sources has been implmenented to support multiple sources assignment simultaneously
