### ISSUE TITLE
maxwell 2d XY and Cylindrical about Z options

### ISSUE THREAD

**Issue by boyang2022** [pyansys/pyaedt#951]
add an option for 2d XY and Cylindrical about Z options in Maxwell 2D

``` python
maxwell_2d = Maxwell2d(solution_type="TransientXY", specified_version="2022.1", non_graphical=False)
```
![image](https://user-images.githubusercontent.com/93125854/158164978-17128490-527b-4998-9595-f4353325a41a.png)

**Comment by MaxJPRey** [comment]
Hi @boyang2022 

The following lines should work:
```
from pyaedt import Maxwell2d
from pyaedt.generic import constants
Maxwell2d(specified_version="2022.1",solution_type=constants.SOLUTIONS.Maxwell2d.TransientZ)
```

Best Regards.

**Comment by boyang2022** [comment]
@MaxJPRey thanks!
