### ISSUE TITLE
Adding optimization setup using pyaedt 

### ISSUE THREAD

**Issue by zebanaqviWAT** [pyansys/pyaedt#961]
Please add more arguments needed to setup an optimization like optimization algorithm, while setting it up.
Need a little more documentation on how to setup a typical optimization in HFSS.

**Comment by maxcapodi78** [comment]
@zebanaqviWAT I'm refactoring Optimetrics Classes in Pyaedt. I'll inform when done

**Comment by maxcapodi78** [comment]
I've refactored Optimetrics, new methods and updated examples will arrive with new version this week
