### ISSUE TITLE
Issue with simulation context definition in optimization goal 

### ISSUE THREAD

**Issue by zebanaqviWAT** [pyansys/pyaedt#965]
There doesn't seem to be an argument in add_optimization() and other related optimization functions, that accepts simulation context (e.g. Infinite Sphere). Only 'domain' is available, which probably should be simulation context instead.

Once this is corrected, would need to know how to add multiple 'Calc. Range',  for eg. Theta(-10deg:10deg), Phi("0deg"),Freq(10GHz) in the goal.

**Comment by maxcapodi78** [comment]
@zebanaqviWAT  I'm refactoring Optimetrics Classes in Pyaedt. I'll inform when done
