### ISSUE TITLE
How to load Parametric From File?

### ISSUE THREAD

**Issue by BLeistr** [pyansys/pyaedt#971]
Is there a way to determine the variables for a Parametric calculation from a file? 
Parametric From File...

thanks a lot

**Comment by maxcapodi78** [comment]
@BLeistr  I'm refactoring Optimetrics Classes in Pyaedt. I'll make sure to add such feature in new classes.

**Comment by maxcapodi78** [comment]
Hello @BLeistr I've implemented a method called add_from_file

you reach it from parametrics property
example:
aedtapp=Hfss()
aedtapp.parametrics.add_from_file("myfile.csv", "MyParametricFromFile")
